"""
This type stub file was generated by pyright.
"""

import json
from json_stream import to_standard_types
from json_stream.base import StreamingJSONBase

_original_default = ...
class JSONStreamEncoder(json.JSONEncoder):
    def default(self, obj): # -> list[Any] | dict[Any, Any] | Any:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


default = ...
