"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import Any, Iterator, Mapping, Sequence

class TransientAccessException(Exception):
    ...


class StreamingJSONBase(ABC):
    INCOMPLETE_ERROR = ...
    @classmethod
    def factory(cls, token, token_stream, persistent): # -> PersistentStreamingJSONObject | PersistentStreamingJSONList | TransientStreamingJSONObject | TransientStreamingJSONList:
        ...
    
    _persistent_children: bool
    def __init__(self, token_stream) -> None:
        ...
    
    def read_all(self): # -> None:
        ...
    
    def __getitem__(self, k) -> Any:
        ...
    
    def __iter__(self) -> Iterator[str]:
        ...
    
    def __copy__(self):
        ...
    
    def __deepcopy__(self, memo):
        ...
    


class PersistentStreamingJSONBase(StreamingJSONBase, ABC):
    def __init__(self, token_stream) -> None:
        ...
    
    def transient(self): # -> Self:
        ...
    
    def __iter__(self): # -> chain[Any]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class TransientStreamingJSONBase(StreamingJSONBase, ABC):
    def __init__(self, token_stream) -> None:
        ...
    
    def __getitem__(self, k) -> Any:
        ...
    
    def __iter__(self):
        ...
    
    def persistent(self): # -> Self:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class StreamingJSONList(StreamingJSONBase, ABC):
    INCOMPLETE_ERROR = ...


@Sequence.register
class PersistentStreamingJSONList(PersistentStreamingJSONBase, StreamingJSONList):
    def __getitem__(self, k) -> Any:
        ...
    


@Sequence.register
class TransientStreamingJSONList(TransientStreamingJSONBase, StreamingJSONList):
    def __init__(self, token_stream) -> None:
        ...
    


class StreamingJSONObject(StreamingJSONBase, ABC):
    INCOMPLETE_ERROR = ...
    def items(self):
        ...
    
    def keys(self):
        ...
    
    def values(self):
        ...
    
    def get(self, k, default=...) -> Any:
        ...
    


@Mapping.register
class PersistentStreamingJSONObject(PersistentStreamingJSONBase, StreamingJSONObject):
    def items(self): # -> chain[Any]:
        ...
    
    def keys(self): # -> chain[Any]:
        ...
    
    def values(self): # -> chain[Any]:
        ...
    
    def __getitem__(self, k) -> Any:
        ...
    


@Mapping.register
class TransientStreamingJSONObject(TransientStreamingJSONBase, StreamingJSONObject):
    def items(self): # -> Generator[Any, Any, None]:
        ...
    
    def keys(self): # -> Generator[Any, None, None]:
        ...
    
    def values(self): # -> Generator[Any, None, None]:
        ...
    


