"""
This type stub file was generated by pyright.
"""

import io

class IterableStream(io.RawIOBase):
    def __init__(self, iterable) -> None:
        ...
    
    def readinto(self, buffer): # -> int:
        ...
    
    def readable(self): # -> Literal[True]:
        ...
    


def ensure_file(fp_or_iterable): # -> IterableStream:
    ...

