"""
This type stub file was generated by pyright.
"""

def load(fp_or_iterable, persistent=..., tokenizer=...): # -> PersistentStreamingJSONObject | PersistentStreamingJSONList | TransientStreamingJSONObject | TransientStreamingJSONList | int:
    ...

def load_many(fp_or_iterable, persistent=..., tokenizer=...): # -> Generator[PersistentStreamingJSONObject | PersistentStreamingJSONList | TransientStreamingJSONObject | TransientStreamingJSONList | int | Any, Any, None]:
    ...

