"""
This type stub file was generated by pyright.
"""

def visit_many(fp_or_iterator, visitor, tokenizer=...): # -> Generator[None, Any, None]:
    ...

def visit(fp_or_iterator, visitor, tokenizer=...): # -> None:
    ...

