"""
This type stub file was generated by pyright.
"""

class Streamable:
    def __init__(self, iterable, *args, **kwargs) -> None:
        ...
    
    def __iter__(self): # -> Self:
        ...
    
    def __next__(self):
        ...
    
    def __bool__(self): # -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class StreamableList(Streamable, list):
    """
        Class specifically designed to pass isinstance(o, list)
        and conform to the implementation of json.dump(o)
        for lists, except items are provided by passed in
        generator
    """
    ...


class StreamableDict(Streamable, dict):
    """
        Class specifically designed to pass isinstance(o, dict)
        and conform to the implementation of json.dump(o)
        for lists, except items are provided by passed in
        generator. Generator must produce pairs of key/value
    """
    def __init__(self, iterable) -> None:
        ...
    
    def items(self): # -> Self:
        ...
    


def streamable_dict(fn): # -> StreamableDict | _Wrapped[Callable[..., Any], object, Callable[..., Any], StreamableDict]:
    ...

def streamable_list(fn): # -> StreamableList | _Wrapped[Callable[..., Any], object, Callable[..., Any], StreamableList]:
    ...

__all__ = ['streamable_dict', 'streamable_list']
