"""
This type stub file was generated by pyright.
"""

import json
from io import BytesIO, StringIO
from itertools import zip_longest
from unittest import TestCase
from json_stream.select_tokenizer import default_tokenizer
from json_stream import load
from json_stream.base import TransientAccessException

class JSONLoadTestCase(TestCase):
    ...


