"""
This type stub file was generated by pyright.
"""

import json_stream
from json_stream.select_tokenizer import default_tokenizer

CONTENT_CHUNK_SIZE = ...
def load(response, persistent=..., tokenizer=..., chunk_size=...): # -> PersistentStreamingJSONObject | PersistentStreamingJSONList | TransientStreamingJSONObject | TransientStreamingJSONList | int:
    ...

def load_many(response, persistent=..., tokenizer=..., chunk_size=...): # -> Generator[PersistentStreamingJSONObject | PersistentStreamingJSONList | TransientStreamingJSONObject | TransientStreamingJSONList | int | Any, Any, None]:
    ...

def visit(response, visitor, tokenizer=..., chunk_size=...): # -> None:
    ...

def visit_many(response, visitor, tokenizer=..., chunk_size=...): # -> Generator[None, Any, None]:
    ...

