from types import CodeType
from typing import Any, Callable, Iterable, TypeVar, overload
from contextlib import AbstractContextManager

from _typeshed import ReadableBuffer

T = TypeVar("T")
F = TypeVar("F")
R = TypeVar("R")

class LoopBreak(Exception): ...
class LoopContinue(Exception): ...

class _MagicNamesMap:
    @overload
    def __getitem__(self, key: str) -> Any: ...
    @overload
    def __getitem__(self, key: tuple[str, ...]) -> tuple[Any, ...]: ...
    def __getattr__(self, key: str) -> Any: ...
    def __call__(self, key: str) -> Any: ...

names: _MagicNamesMap

def evaluate(
    code: str | ReadableBuffer | CodeType,
    /,
    globals: dict[str, Any] | None = ...,
    locals: dict[str, Any] | None = ...,
) -> Any: ...
def execute(
    code: str | ReadableBuffer | CodeType,
    /,
    globals: dict[str, Any] | None = ...,
    locals: dict[str, Any] | None = ...,
) -> dict[str, Any]: ...
def cc_exec(code: str) -> CodeType: ...
def cc_eval(code: str) -> CodeType: ...
def nil(*args: Any, **kwargs: Any) -> None: ...
def simple_cond(
    cond: Any, true: Callable[[], T], false: Callable[[], F] = ...
) -> T | F: ...
def and_gate(a: Any, b: Any) -> Any: ...
def or_gate(a: Any, b: Any) -> Any: ...
def not_gate(a: Any) -> bool: ...
def xor_gate(a: Any, b: Any) -> bool: ...
def nand_gate(a: Any, b: Any) -> bool: ...
def nor_gate(a: Any, b: Any) -> bool: ...
def xnor_gate(a: Any, b: Any) -> bool: ...
def complex_cond(*args: Any) -> Any: ...
def meanwhile(
    cond: Callable[[], Any],
    body: Callable[[], Any],
    else_: Callable[[], Any] | None = ...,
) -> None: ...
def foreach(
    iterable: Iterable[T],
    body: Callable[[T], Any],
    else_: Callable[[], Any] | None = ...,
) -> None: ...
def error(exc: BaseException, from_: BaseException | None = ...) -> Any: ...
def on_error(
    func: Callable[[], T],
    /,
    *handlers_args: tuple[
        type[BaseException] | tuple[type[BaseException], ...],
        Callable[[BaseException], Any],
    ],
    else_block: Callable[[], Any] | None = ...,
    finally_block: Callable[[], Any] | None = ...,
) -> T | Any: ...
def context_manager(
    object: AbstractContextManager[T],
    container: Callable[[T], R],
) -> R | None: ...
def assertion(condition: Any, message: object = ...) -> None: ...
def asyncize(f: Callable[..., T]) -> Callable[..., Any]: ...
def syncize(f: Callable[..., Any]) -> Callable[..., Any]: ...
def cls(
    name: str,
    bases: tuple[type, ...] = ...,
    namespace: dict[str, Any] | None = ...,
    extra_body: Callable[[dict[str, Any]], Any] | None = ...,
    kwds: dict[str, Any] | None = ...,
) -> type: ...
