# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/microsoft/pyright/main/packages/vscode-pyright/schemas/pyrightconfig.schema.json
#   timestamp: 2026-03-07T10:11:32+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel as _BaseModel, ConfigDict, Field, RootModel
from enum import Enum


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        extra="ignore",
        populate_by_name=True,
    )


class Diagnostic1(Enum):
    none = "none"
    information = "information"
    warning = "warning"
    error = "error"


class ExcludeItem(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern="^(.*)$", title="File or directory to exclude from type analysis"
        ),
    ]


class ExecutionEnvironment(BaseModel):
    root: Annotated[
        str,
        Field(
            pattern="^(.*)$",
            title="Path to code subdirectory to which these settings apply",
        ),
    ] = ""
    disableBytesTypePromotions: Annotated[
        bool | None,
        Field(
            title="Do not treat `bytearray` and `memoryview` as implicit subtypes of `bytes`"
        ),
    ] = True
    strictListInference: Annotated[
        bool | None, Field(title="Infer strict types for list expressions")
    ] = False
    strictSetInference: Annotated[
        bool | None, Field(title="Infer strict types for set expressions")
    ] = False
    strictDictionaryInference: Annotated[
        bool | None, Field(title="Infer strict types for dictionary expressions")
    ] = False
    analyzeUnannotatedFunctions: Annotated[
        bool | None,
        Field(
            title="Analyze and report diagnostics for functions that have no annotations"
        ),
    ] = True
    strictParameterNoneValue: Annotated[
        bool | None,
        Field(title="Allow implicit Optional when default parameter value is None"),
    ] = True
    enableExperimentalFeatures: Annotated[
        bool | None,
        Field(
            title="Enable the use of experimental features that are not part of the Python typing spec"
        ),
    ] = False
    enableTypeIgnoreComments: Annotated[
        bool | None, Field(title='Allow "# type: ignore" comments')
    ] = True
    enableReachabilityAnalysis: Annotated[
        bool | None,
        Field(title="Identify code determined to be unreachable through type analysis"),
    ] = True
    deprecateTypingAliases: Annotated[
        bool | None,
        Field(title="Treat typing-specific aliases to standard types as deprecated"),
    ] = False
    reportGeneralTypeIssues: Annotated[
        bool | Diagnostic1 | None,
        Field(title="Controls reporting of general type issues", union_mode="smart"),
    ] = "error"
    reportPropertyTypeMismatch: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of property getter/setter type mismatches",
            union_mode="smart",
        ),
    ] = "none"
    reportFunctionMemberAccess: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of member accesses on function objects",
            union_mode="smart",
        ),
    ] = "error"
    reportMissingImports: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of imports that cannot be resolved",
            union_mode="smart",
        ),
    ] = "error"
    reportMissingModuleSource: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of imports that cannot be resolved to source files",
            union_mode="smart",
        ),
    ] = "warning"
    reportInvalidTypeForm: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of type expressions that use an invalid form",
            union_mode="smart",
        ),
    ] = "error"
    reportMissingTypeStubs: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of imports that cannot be resolved to type stub files",
            union_mode="smart",
        ),
    ] = "none"
    reportImportCycles: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of module imports that create cycles in import graph",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedImport: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of imported symbols that are not referenced within the source file",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedClass: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of private classes that are not accessed",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedFunction: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of private functions or methods that are not accessed",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of local variables that are not accessed",
            union_mode="smart",
        ),
    ] = "none"
    reportDuplicateImport: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of symbols or modules that are imported more than once",
            union_mode="smart",
        ),
    ] = "none"
    reportWildcardImportFromLibrary: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of wildcard import from external library",
            union_mode="smart",
        ),
    ] = "warning"
    reportAbstractUsage: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempted instantiation of abstract class",
            union_mode="smart",
        ),
    ] = "error"
    reportArgumentType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of incompatible argument type", union_mode="smart"
        ),
    ] = "error"
    reportAssertTypeFailure: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of type mismatch detected by typing.assert_type call",
            union_mode="smart",
        ),
    ] = "error"
    reportAssignmentType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of type incompatibilities for assignments",
            union_mode="smart",
        ),
    ] = "error"
    reportAttributeAccessIssue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of issues related to attribute accesses",
            union_mode="smart",
        ),
    ] = "error"
    reportCallIssue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of issues related to call expressions and arguments",
            union_mode="smart",
        ),
    ] = "error"
    reportInconsistentOverload: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of inconsistencies between function overload signatures",
            union_mode="smart",
        ),
    ] = "error"
    reportIndexIssue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of issues related to index operations and expressions",
            union_mode="smart",
        ),
    ] = "error"
    reportInvalidTypeArguments: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of invalid type argument usage",
            union_mode="smart",
        ),
    ] = "error"
    reportNoOverloadImplementation: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of an overloaded function or method with a missing implementation",
            union_mode="smart",
        ),
    ] = "error"
    reportOperatorIssue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of diagnostics related to unary and binary operators",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalSubscript: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to subscript (index) a variable with Optional type",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalMemberAccess: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to access a member of a variable with Optional type",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalCall: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to call a variable with Optional type",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalIterable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an Optional type as an iterable value",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalContextManager: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an Optional type as a parameter to a with statement",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalOperand: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an Optional type as an operand for a binary or unary operator",
            union_mode="smart",
        ),
    ] = "error"
    reportRedeclaration: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to declare the type of a symbol multiple times",
            union_mode="smart",
        ),
    ] = "error"
    reportReturnType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of function return type incompatibility",
            union_mode="smart",
        ),
    ] = "error"
    reportTypedDictNotRequiredAccess: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to access a non-required key in a TypedDict without a check for its presence",
            union_mode="smart",
        ),
    ] = "error"
    reportUntypedFunctionDecorator: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of function decorators without type annotations, which obscure function types",
            union_mode="smart",
        ),
    ] = "none"
    reportUntypedClassDecorator: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of class decorators without type annotations, which obscure class types",
            union_mode="smart",
        ),
    ] = "none"
    reportUntypedBaseClass: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of a base class of an unknown type, which obscures most type checking for the class",
            union_mode="smart",
        ),
    ] = "none"
    reportUntypedNamedTuple: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of a named tuple definition that does not contain type information",
            union_mode="smart",
        ),
    ] = "none"
    reportPrivateUsage: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of private variables and functions used outside of the owning class or module and usage of protected members outside of subclasses",
            union_mode="smart",
        ),
    ] = "none"
    reportTypeCommentUsage: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of deprecated type comment usage",
            union_mode="smart",
        ),
    ] = "none"
    reportPrivateImportUsage: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title='Controls reporting of improper usage of symbol imported from a "py.typed" module that is not re-exported from that module',
            union_mode="smart",
        ),
    ] = "error"
    reportConstantRedefinition: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to redefine variables that are in all-caps",
            union_mode="smart",
        ),
    ] = "none"
    reportDeprecated: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of use of deprecated class or function",
            union_mode="smart",
        ),
    ] = "none"
    reportIncompatibleMethodOverride: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of method overrides in subclasses that redefine the method in an incompatible way",
            union_mode="smart",
        ),
    ] = "error"
    reportIncompatibleVariableOverride: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of overrides in subclasses that redefine a variable in an incompatible way",
            union_mode="smart",
        ),
    ] = "error"
    reportInconsistentConstructor: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of __init__ and __new__ methods whose signatures are inconsistent",
            union_mode="smart",
        ),
    ] = "none"
    reportOverlappingOverload: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of function overloads that overlap in signature and obscure each other or do not agree on return type",
            union_mode="smart",
        ),
    ] = "error"
    reportPossiblyUnboundVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use variable that is possibly unbound on some code paths",
            union_mode="smart",
        ),
    ] = "error"
    reportMissingSuperCall: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of missing call to parent class for inherited `__init__` methods",
            union_mode="smart",
        ),
    ] = "none"
    reportUninitializedInstanceVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of instance variables that are not initialized in the constructor",
            union_mode="smart",
        ),
    ] = "none"
    reportInvalidStringEscapeSequence: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of invalid escape sequences used within string literals",
            union_mode="smart",
        ),
    ] = "warning"
    reportUnknownParameterType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting input and return parameters whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportUnknownArgumentType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting argument expressions whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportUnknownLambdaType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting input and return parameters for lambdas whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportUnknownVariableType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting local variables whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportUnknownMemberType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting class and instance variables whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportMissingParameterType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting input parameters that are missing a type annotation",
            union_mode="smart",
        ),
    ] = "none"
    reportMissingTypeArgument: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting generic class reference with missing type arguments",
            union_mode="smart",
        ),
    ] = "none"
    reportInvalidTypeVarUse: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting improper use of type variables within function signatures",
            union_mode="smart",
        ),
    ] = "warning"
    reportCallInDefaultInitializer: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting usage of function calls within a default value initializer expression",
            union_mode="smart",
        ),
    ] = "none"
    reportUnnecessaryIsInstance: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting calls to 'isinstance' or 'issubclass' where the result is statically determined to be always (or never) true",
            union_mode="smart",
        ),
    ] = "none"
    reportUnnecessaryCast: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting calls to 'cast' that are unnecessary",
            union_mode="smart",
        ),
    ] = "none"
    reportUnnecessaryComparison: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting the use of '==' or '!=' comparisons that are unnecessary",
            union_mode="smart",
        ),
    ] = "none"
    reportUnnecessaryContains: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting the use of 'in' operations that are unnecessary",
            union_mode="smart",
        ),
    ] = "none"
    reportAssertAlwaysTrue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting assert expressions that will always evaluate to true",
            union_mode="smart",
        ),
    ] = "warning"
    reportSelfClsParameterName: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting missing or misnamed self parameters",
            union_mode="smart",
        ),
    ] = "warning"
    reportImplicitStringConcatenation: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting usage of implicit concatenation of string literals",
            union_mode="smart",
        ),
    ] = "none"
    reportUnboundVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an unbound variable",
            union_mode="smart",
        ),
    ] = "error"
    reportUnhashable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of unhashable object in container that requires hashability",
            union_mode="smart",
        ),
    ] = "error"
    reportUndefinedVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an undefined variable",
            union_mode="smart",
        ),
    ] = "error"
    reportInvalidStubStatement: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of type stub statements that do not conform to PEP 484",
            union_mode="smart",
        ),
    ] = "none"
    reportIncompleteStub: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of incomplete type stubs that declare a module-level __getattr__ function",
            union_mode="smart",
        ),
    ] = "none"
    reportUnsupportedDunderAll: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of unsupported operations performed on __all__",
            union_mode="smart",
        ),
    ] = "warning"
    reportUnusedCallResult: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of call expressions whose results are not consumed",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedCoroutine: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of call expressions that returns Coroutine whose results are not consumed",
            union_mode="smart",
        ),
    ] = "error"
    reportUnusedExcept: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of unreachable except clauses", union_mode="smart"
        ),
    ] = "error"
    reportUnusedExpression: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of simple expressions whose value is not used in any way",
            union_mode="smart",
        ),
    ] = "warning"
    reportUnnecessaryTypeIgnoreComment: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of '# type: ignore' comments that have no effect'",
            union_mode="smart",
        ),
    ] = "none"
    reportMatchNotExhaustive: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of 'match' statements that do not exhaustively match all possible values",
            union_mode="smart",
        ),
    ] = "none"
    reportUnreachable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of code that is determined by type analysis to be unreachable",
            union_mode="smart",
        ),
    ] = "none"
    reportImplicitOverride: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting overridden methods that are missing an `@override` decorator",
            union_mode="smart",
        ),
    ] = "none"
    extraPaths: Annotated[
        list[ExtraPath] | None, Field(title="Additional import search resolution paths")
    ] = None
    pythonVersion: Annotated[
        str | None,
        Field(
            examples=["3.7"],
            pattern="^3\\.[0-9]+$",
            title="Python version to assume during type analysis",
        ),
    ] = ""
    """
    Example: '3.7'
    """

    pythonPlatform: Annotated[
        str | None,
        Field(
            examples=["Linux"],
            pattern="^(Linux|Windows|Darwin|iOS|Android|All)$",
            title="Python platform to assume during type analysis",
        ),
    ] = ""
    """
    Example: 'Linux'
    """


class ExtraPath(RootModel[str]):
    root: Annotated[
        str, Field(pattern="^(.*)$", title="Additional import search resolution path")
    ] = ""


class IgnoreItem(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern="^(.*)$",
            title="File or directory where diagnostics should be suppressed",
        ),
    ]


class IncludeItem(RootModel[str]):
    root: Annotated[
        str,
        Field(pattern="^(.*)$", title="File or directory to include in type analysis"),
    ]


class Model(BaseModel):
    """
    Pyright Configuration Schema
    """

    extends: Annotated[
        str | None,
        Field(
            pattern="^(.*)$",
            title="Path to configuration file that this configuration extends",
        ),
    ] = None
    include: Annotated[
        list[IncludeItem] | None,
        Field(title="Files and directories included in type analysis"),
    ] = None
    exclude: Annotated[
        list[ExcludeItem] | None,
        Field(title="Files and directories excluded from type analysis"),
    ] = None
    ignore: Annotated[
        list[IgnoreItem] | None,
        Field(title="Files and directories whose diagnostics are suppressed"),
    ] = None
    strict: Annotated[
        list[StrictItem] | None,
        Field(
            title="Files and directories that should use 'strict' type checking rules"
        ),
    ] = None
    defineConstant: Annotated[
        dict[str, str | bool] | None,
        Field(title="Identifiers that should be treated as constants"),
    ] = None
    typeCheckingMode: Annotated[
        TypeCheckingMode,
        Field(title="Specifies the default rule set to use for type checking"),
    ] = "standard"
    useLibraryCodeForTypes: Annotated[
        bool,
        Field(
            title="Use library implementations to extract type information when type stub is not present"
        ),
    ] = True
    typeshedPath: Annotated[
        str,
        Field(
            pattern="^(.*)$",
            title="Path to directory containing typeshed type stub files",
        ),
    ] = ""
    stubPath: Annotated[
        str,
        Field(
            examples=["src/typestubs"],
            pattern="^(.*)$",
            title="Path to directory containing custom type stub files",
        ),
    ] = "./typings"
    """
    Example: 'src/typestubs'
    """

    disableBytesTypePromotions: Annotated[
        bool | None,
        Field(
            title="Do not treat `bytearray` and `memoryview` as implicit subtypes of `bytes`"
        ),
    ] = True
    strictListInference: Annotated[
        bool | None, Field(title="Infer strict types for list expressions")
    ] = False
    strictSetInference: Annotated[
        bool | None, Field(title="Infer strict types for set expressions")
    ] = False
    strictDictionaryInference: Annotated[
        bool | None, Field(title="Infer strict types for dictionary expressions")
    ] = False
    analyzeUnannotatedFunctions: Annotated[
        bool | None,
        Field(
            title="Analyze and report diagnostics for functions that have no annotations"
        ),
    ] = True
    strictParameterNoneValue: Annotated[
        bool | None,
        Field(title="Allow implicit Optional when default parameter value is None"),
    ] = True
    enableExperimentalFeatures: Annotated[
        bool | None,
        Field(
            title="Enable the use of experimental features that are not part of the Python typing spec"
        ),
    ] = False
    enableTypeIgnoreComments: Annotated[
        bool | None, Field(title='Allow "# type: ignore" comments')
    ] = True
    enableReachabilityAnalysis: Annotated[
        bool | None,
        Field(title="Identify code determined to be unreachable through type analysis"),
    ] = True
    deprecateTypingAliases: Annotated[
        bool | None,
        Field(title="Treat typing-specific aliases to standard types as deprecated"),
    ] = False
    reportGeneralTypeIssues: Annotated[
        bool | Diagnostic1 | None,
        Field(title="Controls reporting of general type issues", union_mode="smart"),
    ] = "error"
    reportPropertyTypeMismatch: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of property getter/setter type mismatches",
            union_mode="smart",
        ),
    ] = "none"
    reportFunctionMemberAccess: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of member accesses on function objects",
            union_mode="smart",
        ),
    ] = "error"
    reportMissingImports: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of imports that cannot be resolved",
            union_mode="smart",
        ),
    ] = "error"
    reportMissingModuleSource: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of imports that cannot be resolved to source files",
            union_mode="smart",
        ),
    ] = "warning"
    reportInvalidTypeForm: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of type expressions that use an invalid form",
            union_mode="smart",
        ),
    ] = "error"
    reportMissingTypeStubs: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of imports that cannot be resolved to type stub files",
            union_mode="smart",
        ),
    ] = "none"
    reportImportCycles: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of module imports that create cycles in import graph",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedImport: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of imported symbols that are not referenced within the source file",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedClass: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of private classes that are not accessed",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedFunction: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of private functions or methods that are not accessed",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of local variables that are not accessed",
            union_mode="smart",
        ),
    ] = "none"
    reportDuplicateImport: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of symbols or modules that are imported more than once",
            union_mode="smart",
        ),
    ] = "none"
    reportWildcardImportFromLibrary: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of wildcard import from external library",
            union_mode="smart",
        ),
    ] = "warning"
    reportAbstractUsage: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempted instantiation of abstract class",
            union_mode="smart",
        ),
    ] = "error"
    reportArgumentType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of incompatible argument type", union_mode="smart"
        ),
    ] = "error"
    reportAssertTypeFailure: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of type mismatch detected by typing.assert_type call",
            union_mode="smart",
        ),
    ] = "error"
    reportAssignmentType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of type incompatibilities for assignments",
            union_mode="smart",
        ),
    ] = "error"
    reportAttributeAccessIssue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of issues related to attribute accesses",
            union_mode="smart",
        ),
    ] = "error"
    reportCallIssue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of issues related to call expressions and arguments",
            union_mode="smart",
        ),
    ] = "error"
    reportInconsistentOverload: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of inconsistencies between function overload signatures",
            union_mode="smart",
        ),
    ] = "error"
    reportIndexIssue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of issues related to index operations and expressions",
            union_mode="smart",
        ),
    ] = "error"
    reportInvalidTypeArguments: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of invalid type argument usage",
            union_mode="smart",
        ),
    ] = "error"
    reportNoOverloadImplementation: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of an overloaded function or method with a missing implementation",
            union_mode="smart",
        ),
    ] = "error"
    reportOperatorIssue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of diagnostics related to unary and binary operators",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalSubscript: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to subscript (index) a variable with Optional type",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalMemberAccess: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to access a member of a variable with Optional type",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalCall: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to call a variable with Optional type",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalIterable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an Optional type as an iterable value",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalContextManager: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an Optional type as a parameter to a with statement",
            union_mode="smart",
        ),
    ] = "error"
    reportOptionalOperand: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an Optional type as an operand for a binary or unary operator",
            union_mode="smart",
        ),
    ] = "error"
    reportRedeclaration: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to declare the type of a symbol multiple times",
            union_mode="smart",
        ),
    ] = "error"
    reportReturnType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of function return type incompatibility",
            union_mode="smart",
        ),
    ] = "error"
    reportTypedDictNotRequiredAccess: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to access a non-required key in a TypedDict without a check for its presence",
            union_mode="smart",
        ),
    ] = "error"
    reportUntypedFunctionDecorator: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of function decorators without type annotations, which obscure function types",
            union_mode="smart",
        ),
    ] = "none"
    reportUntypedClassDecorator: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of class decorators without type annotations, which obscure class types",
            union_mode="smart",
        ),
    ] = "none"
    reportUntypedBaseClass: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of a base class of an unknown type, which obscures most type checking for the class",
            union_mode="smart",
        ),
    ] = "none"
    reportUntypedNamedTuple: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of a named tuple definition that does not contain type information",
            union_mode="smart",
        ),
    ] = "none"
    reportPrivateUsage: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of private variables and functions used outside of the owning class or module and usage of protected members outside of subclasses",
            union_mode="smart",
        ),
    ] = "none"
    reportTypeCommentUsage: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of deprecated type comment usage",
            union_mode="smart",
        ),
    ] = "none"
    reportPrivateImportUsage: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title='Controls reporting of improper usage of symbol imported from a "py.typed" module that is not re-exported from that module',
            union_mode="smart",
        ),
    ] = "error"
    reportConstantRedefinition: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to redefine variables that are in all-caps",
            union_mode="smart",
        ),
    ] = "none"
    reportDeprecated: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of use of deprecated class or function",
            union_mode="smart",
        ),
    ] = "none"
    reportIncompatibleMethodOverride: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of method overrides in subclasses that redefine the method in an incompatible way",
            union_mode="smart",
        ),
    ] = "error"
    reportIncompatibleVariableOverride: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of overrides in subclasses that redefine a variable in an incompatible way",
            union_mode="smart",
        ),
    ] = "error"
    reportInconsistentConstructor: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of __init__ and __new__ methods whose signatures are inconsistent",
            union_mode="smart",
        ),
    ] = "none"
    reportOverlappingOverload: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of function overloads that overlap in signature and obscure each other or do not agree on return type",
            union_mode="smart",
        ),
    ] = "error"
    reportPossiblyUnboundVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use variable that is possibly unbound on some code paths",
            union_mode="smart",
        ),
    ] = "error"
    reportMissingSuperCall: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of missing call to parent class for inherited `__init__` methods",
            union_mode="smart",
        ),
    ] = "none"
    reportUninitializedInstanceVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of instance variables that are not initialized in the constructor",
            union_mode="smart",
        ),
    ] = "none"
    reportInvalidStringEscapeSequence: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of invalid escape sequences used within string literals",
            union_mode="smart",
        ),
    ] = "warning"
    reportUnknownParameterType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting input and return parameters whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportUnknownArgumentType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting argument expressions whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportUnknownLambdaType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting input and return parameters for lambdas whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportUnknownVariableType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting local variables whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportUnknownMemberType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting class and instance variables whose types are unknown",
            union_mode="smart",
        ),
    ] = "none"
    reportMissingParameterType: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting input parameters that are missing a type annotation",
            union_mode="smart",
        ),
    ] = "none"
    reportMissingTypeArgument: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting generic class reference with missing type arguments",
            union_mode="smart",
        ),
    ] = "none"
    reportInvalidTypeVarUse: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting improper use of type variables within function signatures",
            union_mode="smart",
        ),
    ] = "warning"
    reportCallInDefaultInitializer: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting usage of function calls within a default value initializer expression",
            union_mode="smart",
        ),
    ] = "none"
    reportUnnecessaryIsInstance: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting calls to 'isinstance' or 'issubclass' where the result is statically determined to be always (or never) true",
            union_mode="smart",
        ),
    ] = "none"
    reportUnnecessaryCast: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting calls to 'cast' that are unnecessary",
            union_mode="smart",
        ),
    ] = "none"
    reportUnnecessaryComparison: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting the use of '==' or '!=' comparisons that are unnecessary",
            union_mode="smart",
        ),
    ] = "none"
    reportUnnecessaryContains: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting the use of 'in' operations that are unnecessary",
            union_mode="smart",
        ),
    ] = "none"
    reportAssertAlwaysTrue: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting assert expressions that will always evaluate to true",
            union_mode="smart",
        ),
    ] = "warning"
    reportSelfClsParameterName: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting missing or misnamed self parameters",
            union_mode="smart",
        ),
    ] = "warning"
    reportImplicitStringConcatenation: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting usage of implicit concatenation of string literals",
            union_mode="smart",
        ),
    ] = "none"
    reportUnboundVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an unbound variable",
            union_mode="smart",
        ),
    ] = "error"
    reportUnhashable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of unhashable object in container that requires hashability",
            union_mode="smart",
        ),
    ] = "error"
    reportUndefinedVariable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of attempts to use an undefined variable",
            union_mode="smart",
        ),
    ] = "error"
    reportInvalidStubStatement: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of type stub statements that do not conform to PEP 484",
            union_mode="smart",
        ),
    ] = "none"
    reportIncompleteStub: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of incomplete type stubs that declare a module-level __getattr__ function",
            union_mode="smart",
        ),
    ] = "none"
    reportUnsupportedDunderAll: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of unsupported operations performed on __all__",
            union_mode="smart",
        ),
    ] = "warning"
    reportUnusedCallResult: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of call expressions whose results are not consumed",
            union_mode="smart",
        ),
    ] = "none"
    reportUnusedCoroutine: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of call expressions that returns Coroutine whose results are not consumed",
            union_mode="smart",
        ),
    ] = "error"
    reportUnusedExcept: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of unreachable except clauses", union_mode="smart"
        ),
    ] = "error"
    reportUnusedExpression: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of simple expressions whose value is not used in any way",
            union_mode="smart",
        ),
    ] = "warning"
    reportUnnecessaryTypeIgnoreComment: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of '# type: ignore' comments that have no effect'",
            union_mode="smart",
        ),
    ] = "none"
    reportMatchNotExhaustive: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of 'match' statements that do not exhaustively match all possible values",
            union_mode="smart",
        ),
    ] = "none"
    reportUnreachable: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting of code that is determined by type analysis to be unreachable",
            union_mode="smart",
        ),
    ] = "none"
    reportImplicitOverride: Annotated[
        bool | Diagnostic1 | None,
        Field(
            title="Controls reporting overridden methods that are missing an `@override` decorator",
            union_mode="smart",
        ),
    ] = "none"
    extraPaths: Annotated[
        list[ExtraPath] | None, Field(title="Additional import search resolution paths")
    ] = None
    pythonVersion: Annotated[
        str | None,
        Field(
            examples=["3.7"],
            pattern="^3\\.[0-9]+$",
            title="Python version to assume during type analysis",
        ),
    ] = ""
    """
    Example: '3.7'
    """

    pythonPlatform: Annotated[
        str | None,
        Field(
            examples=["Linux"],
            pattern="^(Linux|Windows|Darwin|iOS|Android|All)$",
            title="Python platform to assume during type analysis",
        ),
    ] = ""
    """
    Example: 'Linux'
    """

    venvPath: Annotated[
        str,
        Field(
            pattern="^(.*)$",
            title="Path to directory containing a folder of virtual environments",
        ),
    ] = ""
    venv: Annotated[
        str,
        Field(
            examples=["python37"],
            pattern="^(.*)$",
            title="Name of virtual environment subdirectory within venvPath",
        ),
    ] = ""
    """
    Example: 'python37'
    """

    verboseOutput: Annotated[bool, Field(title="Output verbose logging")] = False
    executionEnvironments: Annotated[
        list[ExecutionEnvironment] | None,
        Field(title="Analysis settings to use for specified subdirectories of code"),
    ] = None


class StrictItem(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern="^(.*)$",
            title="File or directory that should use 'strict' type checking rules",
        ),
    ]


class TypeCheckingMode(Enum):
    off = "off"
    basic = "basic"
    standard = "standard"
    strict = "strict"
