from typing import TypeAlias

from distlib.metadata import Metadata

from .util import cached_property
from _typeshed import Incomplete, SupportsWrite
from collections.abc import Generator

__all__ = [
    "DistributionPath",
    "Distribution",
    "BaseInstalledDistribution",
    "InstalledDistribution",
    "EggInfoDistribution",
]

_InstalledDistributionType: TypeAlias = "InstalledDistribution | EggInfoDistribution"

class _Cache:
    name: Incomplete
    path: Incomplete
    generated: bool
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def add(self, dist: _InstalledDistributionType) -> None: ...

class DistributionPath:
    path: list[str]
    def __init__(
        self, path: list[str] | None = None, include_egg: bool = False
    ) -> None: ...
    @property
    def cache_enabled(self) -> bool: ...
    @cache_enabled.setter
    def cache_enabled(self, value: bool) -> None: ...
    def clear_cache(self) -> None: ...
    @classmethod
    def distinfo_dirname(cls, name: str, version: str) -> str: ...
    def get_distributions(
        self,
    ) -> Generator[_InstalledDistributionType]: ...
    def get_distribution(self, name: str) -> _InstalledDistributionType | None: ...
    def provides_distribution(
        self, name: str, version: str | None = None
    ) -> Generator[_InstalledDistributionType]: ...
    def get_file_path(self, name: str, relative_path: str) -> str: ...
    def get_exported_entries(
        self, category: str, name: str | None = None
    ) -> Generator[Incomplete]: ...

class Distribution:
    build_time_dependency: bool
    requested: bool
    metadata: Metadata
    name: str
    key: str
    version: str
    locator: Incomplete
    digest: Incomplete
    extras: Incomplete
    context: Incomplete
    download_urls: set[Incomplete]
    digests: dict[Incomplete, Incomplete]
    def __init__(self, metadata: Metadata) -> None: ...
    @property
    def source_url(self) -> str: ...
    download_url = source_url
    @property
    def name_and_version(self) -> str: ...
    @property
    def provides(self) -> set[str]: ...
    @property
    def run_requires(self) -> set[str]: ...
    @property
    def meta_requires(self) -> set[str]: ...
    @property
    def build_requires(self) -> set[str]: ...
    @property
    def test_requires(self) -> set[str]: ...
    @property
    def dev_requires(self) -> set[str]: ...
    def matches_requirement(self, req: str) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BaseInstalledDistribution(Distribution):
    hasher: str | None
    path: str
    dist_path: DistributionPath | None
    def __init__(
        self, metadata: Metadata, path: str, env: DistributionPath | None = None
    ) -> None: ...
    def get_hash(self, data: bytes, hasher: str | None = None) -> str: ...

class InstalledDistribution(BaseInstalledDistribution):
    hasher: str | None
    modules: Incomplete
    finder: Incomplete
    requested: Incomplete
    def __init__(
        self,
        path: str,
        metadata: Metadata | None = None,
        env: DistributionPath | None = None,
    ) -> None: ...
    @cached_property
    def exports(self) -> dict[Incomplete, Incomplete]: ...
    def read_exports(self) -> dict[Incomplete, Incomplete]: ...
    def write_exports(self, exports: dict[Incomplete, Incomplete]) -> None: ...
    def get_resource_path(self, relative_path: str) -> str: ...
    def list_installed_files(self) -> Generator[Incomplete]: ...
    def write_installed_files(
        self, paths: list[str], prefix: str, dry_run: bool = False
    ) -> None: ...
    def check_installed_files(self) -> None: ...
    @cached_property
    def shared_locations(self) -> dict[str, Incomplete]: ...
    def write_shared_locations(
        self, paths: dict[str, Incomplete], dry_run: bool = False
    ) -> None: ...
    def get_distinfo_resource(self, path: str) -> str: ...
    def get_distinfo_file(self, path: str) -> str: ...
    def list_distinfo_files(self) -> Generator[Incomplete]: ...
    def __eq__(self, other: object) -> bool: ...
    __hash__ = object.__hash__

class EggInfoDistribution(BaseInstalledDistribution):
    requested: bool
    shared_locations: Incomplete
    path: str
    dist_path: DistributionPath | None
    def __init__(self, path: str, env: DistributionPath | None = None) -> None: ...
    def check_installed_files(self) -> list[tuple[str, str, bool, bool]]: ...
    def list_installed_files(self) -> Generator[tuple[str, str, int]]: ...
    def list_distinfo_files(
        self, absolute: bool = False
    ) -> Generator[str, None, None]: ...
    def __eq__(self, other: object) -> bool: ...
    __hash__ = object.__hash__

new_dist_class = InstalledDistribution
old_dist_class = EggInfoDistribution

class DependencyGraph:
    adjacency_list: dict[_InstalledDistributionType, list[str]]
    reverse_list: dict[_InstalledDistributionType, list[str]]
    missing: dict[_InstalledDistributionType, list[str]]
    def __init__(self) -> None: ...
    def add_distribution(self, distribution: _InstalledDistributionType) -> None: ...
    def add_edge(
        self,
        x: _InstalledDistributionType,
        y: _InstalledDistributionType,
        label: str | None = None,
    ) -> None: ...
    def add_missing(
        self, distribution: _InstalledDistributionType, requirement: str
    ) -> None: ...
    def repr_node(self, dist: _InstalledDistributionType, level: int = 1) -> str: ...
    def to_dot(self, f: SupportsWrite[str], skip_disconnected: bool = True) -> None: ...
    def topological_sort(self) -> list[_InstalledDistributionType]: ...
