from _typeshed import Incomplete

__all__ = ["Manifest"]

class Manifest:
    base: Incomplete
    prefix: Incomplete
    allfiles: Incomplete
    files: Incomplete
    def __init__(self, base=None) -> None: ...
    def findall(self) -> None: ...
    def add(self, item) -> None: ...
    def add_many(self, items) -> None: ...
    def sorted(self, wantdirs: bool = False): ...
    def clear(self) -> None: ...
    def process_directive(self, directive) -> None: ...
