from . import DistlibException
from .version import PEP440_VERSION_RE
from _typeshed import Incomplete

__all__ = ["PKG_INFO_ENCODING", "PKG_INFO_PREFERRED_VERSION", "Metadata"]

class MetadataMissingError(DistlibException): ...
class MetadataConflictError(DistlibException): ...
class MetadataUnrecognizedVersionError(DistlibException): ...
class MetadataInvalidError(DistlibException): ...

PKG_INFO_ENCODING: str
PKG_INFO_PREFERRED_VERSION: str

class LegacyMetadata:
    requires_files: Incomplete
    scheme: Incomplete
    def __init__(
        self, path=None, fileobj=None, mapping=None, scheme: str = "default"
    ) -> None: ...
    def set_metadata_version(self) -> None: ...
    def __getitem__(self, name): ...
    def __setitem__(self, name, value) -> None: ...
    def __delitem__(self, name) -> None: ...
    def __contains__(self, name) -> bool: ...
    def __getattr__(self, name): ...
    def get_fullname(self, filesafe: bool = False): ...
    def is_field(self, name): ...
    def is_multi_field(self, name): ...
    def read(self, filepath) -> None: ...
    def read_file(self, fileob) -> None: ...
    def write(self, filepath, skip_unknown: bool = False) -> None: ...
    def write_file(self, fileobject, skip_unknown: bool = False) -> None: ...
    def update(self, other=None, **kwargs) -> None: ...
    def set(self, name, value) -> None: ...
    def get(self, name, default=...): ...
    def check(self, strict: bool = False): ...
    def todict(self, skip_missing: bool = False): ...
    def add_requirements(self, requirements) -> None: ...
    def keys(self): ...
    def __iter__(self): ...
    def values(self): ...
    def items(self): ...

class Metadata:
    METADATA_VERSION_MATCHER: Incomplete
    NAME_MATCHER: Incomplete
    FIELDNAME_MATCHER: Incomplete
    VERSION_MATCHER = PEP440_VERSION_RE
    SUMMARY_MATCHER: Incomplete
    METADATA_VERSION: str
    GENERATOR: Incomplete
    MANDATORY_KEYS: Incomplete
    INDEX_KEYS: str
    DEPENDENCY_KEYS: str
    SYNTAX_VALIDATORS: Incomplete
    scheme: Incomplete
    def __init__(
        self, path=None, fileobj=None, mapping=None, scheme: str = "default"
    ) -> None: ...
    common_keys: Incomplete
    none_list: Incomplete
    none_dict: Incomplete
    mapped_keys: Incomplete
    def __getattribute__(self, key): ...
    def __setattr__(self, key, value) -> None: ...
    @property
    def name_and_version(self): ...
    @property
    def provides(self): ...
    @provides.setter
    def provides(self, value) -> None: ...
    def get_requirements(self, reqts, extras=None, env=None): ...
    @property
    def dictionary(self): ...
    @property
    def dependencies(self): ...
    @dependencies.setter
    def dependencies(self, value) -> None: ...
    def validate(self) -> None: ...
    def todict(self): ...
    LEGACY_MAPPING: Incomplete
    def write(
        self, path=None, fileobj=None, legacy: bool = False, skip_unknown: bool = True
    ) -> None: ...
    def add_requirements(self, requirements) -> None: ...
