from . import DistlibException as DistlibException
from .util import (
    Cache as Cache,
    cached_property as cached_property,
    get_cache_base as get_cache_base,
)
from _typeshed import Incomplete
from collections.abc import Generator

logger: Incomplete
cache: Incomplete

class ResourceCache(Cache):
    def __init__(self, base=None) -> None: ...
    def is_stale(self, resource, path): ...
    def get(self, resource): ...

class ResourceBase:
    finder: Incomplete
    name: Incomplete
    def __init__(self, finder, name) -> None: ...

class Resource(ResourceBase):
    is_container: bool
    def as_stream(self): ...
    @cached_property
    def file_path(self): ...
    @cached_property
    def bytes(self): ...
    @cached_property
    def size(self): ...

class ResourceContainer(ResourceBase):
    is_container: bool
    @cached_property
    def resources(self): ...

class ResourceFinder:
    skipped_extensions: Incomplete
    module: Incomplete
    loader: Incomplete
    base: Incomplete
    def __init__(self, module) -> None: ...
    def get_cache_info(self, resource): ...
    def find(self, resource_name): ...
    def get_stream(self, resource): ...
    def get_bytes(self, resource): ...
    def get_size(self, resource): ...
    def get_resources(self, resource): ...
    def is_container(self, resource): ...
    def iterator(self, resource_name) -> Generator[Incomplete]: ...

class ZipResourceFinder(ResourceFinder):
    prefix_len: Incomplete
    index: Incomplete
    def __init__(self, module) -> None: ...
    def get_cache_info(self, resource): ...
    def get_bytes(self, resource): ...
    def get_stream(self, resource): ...
    def get_size(self, resource): ...
    def get_resources(self, resource): ...

def register_finder(loader, finder_maker) -> None: ...
def finder(package): ...
def finder_for_path(path): ...
