import contextlib
import types
from . import DistlibException as DistlibException
from .compat import (
    BaseConfigurator as BaseConfigurator,
    CertificateError as CertificateError,
    Container as Container,
    HTTPHandler as HTTPHandler,
    HTTPSHandler as BaseHTTPSHandler,
    StringIO as StringIO,
    URLError as URLError,
    ZipFile as ZipFile,
    cache_from_source as cache_from_source,
    configparser as configparser,
    fsdecode as fsdecode,
    httplib as httplib,
    match_hostname as match_hostname,
    raw_input as raw_input,
    shutil as shutil,
    string_types as string_types,
    text_type as text_type,
    unquote as unquote,
    urljoin as urljoin,
    urlopen as urlopen,
    urlparse as urlparse,
    valid_ident as valid_ident,
    xmlrpclib as xmlrpclib,
)
from _typeshed import Incomplete
from collections.abc import Generator

logger: Incomplete
IDENTIFIER: Incomplete
VERSION_IDENTIFIER: Incomplete
COMPARE_OP: Incomplete
MARKER_OP: Incomplete
OR: Incomplete
AND: Incomplete
NON_SPACE: Incomplete
STRING_CHUNK: Incomplete

def parse_marker(marker_string): ...
def parse_requirement(req): ...
def get_resources_dests(resources_root, rules): ...
def in_venv(): ...
def get_executable(): ...
def proceed(prompt, allowed_chars, error_prompt=None, default=None): ...
def extract_by_key(d, keys): ...
def read_exports(stream): ...
def write_exports(exports, stream) -> None: ...
@contextlib.contextmanager
def tempdir() -> Generator[Incomplete]: ...
@contextlib.contextmanager
def chdir(d) -> Generator[None]: ...
@contextlib.contextmanager
def socket_timeout(seconds: int = 15) -> Generator[None]: ...

class cached_property:
    func: Incomplete
    def __init__(self, func) -> None: ...
    def __get__(self, obj, cls=None): ...

def convert_path(pathname): ...

class FileOperator:
    dry_run: Incomplete
    ensured: Incomplete
    def __init__(self, dry_run: bool = False) -> None: ...
    def record_as_written(self, path) -> None: ...
    def newer(self, source, target): ...
    def copy_file(self, infile, outfile, check: bool = True) -> None: ...
    def copy_stream(self, instream, outfile, encoding=None) -> None: ...
    def write_binary_file(self, path, data) -> None: ...
    def write_text_file(self, path, data, encoding) -> None: ...
    def set_mode(self, bits, mask, files) -> None: ...
    set_executable_mode: Incomplete
    def ensure_dir(self, path) -> None: ...
    def byte_compile(
        self,
        path,
        optimize: bool = False,
        force: bool = False,
        prefix=None,
        hashed_invalidation: bool = False,
    ): ...
    def ensure_removed(self, path) -> None: ...
    def is_writable(self, path): ...
    def commit(self): ...
    def rollback(self) -> None: ...

def resolve(module_name, dotted_path): ...

class ExportEntry:
    name: Incomplete
    prefix: Incomplete
    suffix: Incomplete
    flags: Incomplete
    def __init__(self, name, prefix, suffix, flags) -> None: ...
    @cached_property
    def value(self): ...
    def __eq__(self, other): ...
    __hash__: Incomplete

ENTRY_RE: Incomplete

def get_export_entry(specification): ...
def get_cache_base(suffix=None): ...
def path_to_cache_dir(path, use_abspath: bool = True): ...
def ensure_slash(s): ...
def parse_credentials(netloc): ...
def get_process_umask(): ...
def is_string_sequence(seq): ...

PROJECT_NAME_AND_VERSION: Incomplete
PYTHON_VERSION: Incomplete

def split_filename(filename, project_name=None): ...

NAME_VERSION_RE: Incomplete

def parse_name_and_version(p): ...
def get_extras(requested, available): ...
def get_project_data(name): ...
def get_package_data(name, version): ...

class Cache:
    base: Incomplete
    def __init__(self, base) -> None: ...
    def prefix_to_dir(self, prefix, use_abspath: bool = True): ...
    def clear(self): ...

class EventMixin:
    def __init__(self) -> None: ...
    def add(self, event, subscriber, append: bool = True) -> None: ...
    def remove(self, event, subscriber) -> None: ...
    def get_subscribers(self, event): ...
    def publish(self, event, *args, **kwargs): ...

class Sequencer:
    def __init__(self) -> None: ...
    def add_node(self, node) -> None: ...
    def remove_node(self, node, edges: bool = False) -> None: ...
    def add(self, pred, succ) -> None: ...
    def remove(self, pred, succ) -> None: ...
    def is_step(self, step): ...
    def get_steps(self, final): ...
    @property
    def strong_connections(self): ...
    @property
    def dot(self): ...

ARCHIVE_EXTENSIONS: Incomplete

def unarchive(archive_filename, dest_dir, format=None, check: bool = True): ...
def zip_dir(directory): ...

UNITS: Incomplete

class Progress:
    unknown: str
    min: Incomplete
    max: Incomplete
    started: Incomplete
    elapsed: int
    done: bool
    def __init__(self, minval: int = 0, maxval: int = 100) -> None: ...
    cur: Incomplete
    def update(self, curval) -> None: ...
    def increment(self, incr) -> None: ...
    def start(self): ...
    def stop(self) -> None: ...
    @property
    def maximum(self): ...
    @property
    def percentage(self): ...
    def format_duration(self, duration): ...
    @property
    def ETA(self): ...
    @property
    def speed(self): ...

RICH_GLOB: Incomplete

def iglob(path_glob): ...

class HTTPSConnection(httplib.HTTPSConnection):
    ca_certs: Incomplete
    check_domain: bool
    sock: Incomplete
    def connect(self) -> None: ...

class HTTPSHandler(BaseHTTPSHandler):
    ca_certs: Incomplete
    check_domain: Incomplete
    def __init__(self, ca_certs, check_domain: bool = True) -> None: ...
    def https_open(self, req): ...

class HTTPSOnlyHandler(HTTPSHandler, HTTPHandler):
    def http_open(self, req) -> None: ...

class Transport(xmlrpclib.Transport):
    timeout: Incomplete
    def __init__(self, timeout, use_datetime: int = 0) -> None: ...
    def make_connection(self, host): ...

class SafeTransport(xmlrpclib.SafeTransport):
    timeout: Incomplete
    def __init__(self, timeout, use_datetime: int = 0) -> None: ...
    def make_connection(self, host): ...

class ServerProxy(xmlrpclib.ServerProxy):
    timeout: Incomplete
    transport: Incomplete
    def __init__(self, uri, **kwargs) -> None: ...

class CSVBase:
    defaults: Incomplete
    def __enter__(self): ...
    def __exit__(self, *exc_info) -> None: ...

class CSVReader(CSVBase):
    stream: Incomplete
    reader: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def __iter__(self): ...
    def next(self): ...
    __next__ = next

class CSVWriter(CSVBase):
    stream: Incomplete
    writer: Incomplete
    def __init__(self, fn, **kwargs) -> None: ...
    def writerow(self, row) -> None: ...

class Configurator(BaseConfigurator):
    value_converters: Incomplete
    base: Incomplete
    def __init__(self, config, base=None) -> None: ...
    def configure_custom(self, config): ...
    def __getitem__(self, key): ...
    def inc_convert(self, value): ...

class SubprocessMixin:
    verbose: Incomplete
    progress: Incomplete
    def __init__(self, verbose: bool = False, progress=None) -> None: ...
    def reader(self, stream, context) -> None: ...
    def run_command(self, cmd, **kwargs): ...

def normalize_name(name): ...

class PyPIRCFile:
    DEFAULT_REPOSITORY: str
    DEFAULT_REALM: str
    filename: Incomplete
    url: Incomplete
    def __init__(self, fn=None, url=None) -> None: ...
    def read(self): ...
    def update(self, username, password) -> None: ...

def get_host_platform(): ...
def get_platform(): ...
