from _typeshed import Incomplete

__all__ = [
    "UnsupportedVersionError",
    "NormalizedVersion",
    "NormalizedMatcher",
    "LegacyVersion",
    "LegacyMatcher",
    "SemanticVersion",
    "SemanticMatcher",
    "get_scheme",
]

class UnsupportedVersionError(ValueError): ...

class Version:
    def __init__(self, s) -> None: ...
    def parse(self, s) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...
    def __hash__(self): ...
    @property
    def is_prerelease(self) -> None: ...

class Matcher:
    version_class: Incomplete
    def parse_requirement(self, s): ...
    name: Incomplete
    key: Incomplete
    def __init__(self, s) -> None: ...
    def match(self, version): ...
    @property
    def exact_version(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class NormalizedVersion(Version):
    def parse(self, s): ...
    PREREL_TAGS: Incomplete
    @property
    def is_prerelease(self): ...

class NormalizedMatcher(Matcher):
    version_class = NormalizedVersion

class LegacyVersion(Version):
    def parse(self, s): ...
    @property
    def is_prerelease(self): ...

class LegacyMatcher(Matcher):
    version_class = LegacyVersion
    numeric_re: Incomplete

class SemanticVersion(Version):
    def parse(self, s): ...
    @property
    def is_prerelease(self): ...

class SemanticMatcher(Matcher):
    version_class = SemanticVersion

class VersionScheme:
    key: Incomplete
    matcher: Incomplete
    suggester: Incomplete
    def __init__(
        self, key: Incomplete, matcher: Incomplete, suggester: Incomplete = None
    ) -> None: ...
    def is_valid_version(self, s: Incomplete) -> bool: ...
    def is_valid_matcher(self, s: Incomplete) -> bool: ...
    def is_valid_constraint_list(self, s: Incomplete) -> bool: ...
    def suggest(self, s: Incomplete) -> Incomplete: ...

def get_scheme(name: str) -> VersionScheme: ...
