# generated by datamodel-codegen:
#   filename:  wmstreams_spec.json
#   timestamp: 2026-02-06T11:01:26+00:00

from __future__ import annotations
from pydantic import (
    AwareDatetime,
    BaseModel as _BaseModel,
    ConfigDict,
    Field,
    RootModel,
)
from typing import Annotated, Any
from enum import Enum


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        extra="ignore",
        populate_by_name=True,
    )


class WikimediaEventStreamAddedLink(BaseModel):
    external: bool | None = None
    """
    Whether link is external
    """

    link: str | None = None
    """
    Link being added
    """


class WikimediaEventStreamChangelogKind(Enum):
    """
    The kind of this event in a changelog. This is used to map the event to an action in a data store.

    """

    insert = "insert"
    update = "update"
    delete = "delete"


class WikimediaEventStreamContentSlots(BaseModel):
    """
    Fields for representing MediaWiki page revision content.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    content_body: str | None = None
    """
    Content body. NOTE: This field is not required, and is often not set in streams as it can make events very large. It is included here for events that do include the content body.

    """

    content_format: str | None = None
    """
    The 'content type' of the content.  E.g. wikitext/html. This is similiar to a MIME type.
    """

    content_model: str | None = None
    """
    MediaWiki's content model of this content. E.g. wikitext, json, etc.
    """

    content_sha1: str | None = None
    """
    sha1 sum of the content body.
    """

    content_size: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    Byte size of the content body.
    """

    origin_rev_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    Revision in which this slot was originally created
    """

    slot_role: str | None = None
    """
    Slot role name.
    """


class WikimediaEventStreamCreatedRedirectPage(BaseModel):
    """
    Page entity that was created at the old title during a page move. This is only set for page move events. Note that the created_redirect_page will also have its own associated page create event.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    is_redirect: bool | None = None
    """
    True if the page is a redirect page at the time of this event.
    """

    namespace_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The id of the namespace this page belongs to.
    """

    page_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) page ID of the page.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page.
    """

    revision_count: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    NOTE: revision_count is never set for created_redirect_page. It is present here for backwards compatibility only.

    """


class WikimediaEventStreamEditor(BaseModel):
    """
    Represents the MediaWiki user that made this edit.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    edit_count: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The number of edits this user has made at the time of this event. Not present for anonymous users.

    """

    groups: list[WikimediaEventStreamUserGroup] | None = None
    """
    A list of the groups this user belongs to.  E.g. bot, sysop etc. Not present for anonymous users.

    """

    is_bot: bool | None = None
    """
    True if this user is considered to be a bot at the time of this event. This is checked via the $user->isBot() method, which considers both user_groups and user permissions.

    """

    is_system: bool | None = None
    """
    True if the user is a MediaWiki 'system' user. These are users that cannot 'authenticate'.  These are usually listed in ReservedUsernames.

    """

    is_temp: bool | None = None
    """
    True if the user is an autocreated temporary MediaWiki user. This is used for IP masking.

    """

    registration_dt: Annotated[AwareDatetime | None, Field(max_length=128)] = None
    """
    The datetime of the user account registration. Not present for anonymous users or if missing in the MW database.

    """

    user_central_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    Global cross-wiki user ID. See: https://www.mediawiki.org/wiki/Manual:Central_ID

    """

    user_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    MediaWiki User ID. This is optional, and will not be present for anonymous users.

    """

    user_text: Annotated[str | None, Field(min_length=1)] = None
    """
    The user name or text representation of the user that performed this change.

    """


class WikimediaEventStreamLength(BaseModel):
    """
    Length of old and new change
    """

    new: int | None = None
    """
    (rc_new_len)
    """

    old: int | None = None
    """
    (rc_old_len)
    """


class WikimediaEventStreamMain(BaseModel):
    """
    Schema fields describing a revision slot
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    rev_slot_content_model: str
    """
    Model of the content (e.g. wikitext, wikibase-mediainfo...)
    """

    rev_slot_origin_rev_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = (
        None
    )
    """
    Revision for which this slot was created
    """

    rev_slot_sha1: str
    """
    SHA1 of the slot content
    """

    rev_slot_size: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    Size in bytes of the slot content
    """


class WikimediaEventStreamMeta(BaseModel):
    domain: Annotated[str | None, Field(min_length=1)] = None
    """
    Domain the event or entity pertains to
    """

    dt: Annotated[AwareDatetime | None, Field(max_length=128)] = None
    """
    Time the event was received by the system, in UTC ISO-8601 format
    """

    id: str | None = None
    """
    Unique ID of this event
    """

    request_id: str | None = None
    """
    Unique ID of the request that caused the event
    """

    stream: Annotated[str, Field(min_length=1)]
    """
    Name of the stream (dataset) that this event belongs in
    """

    uri: Annotated[str | None, Field(max_length=8192)] = None
    """
    Unique URI identifying the event or entity
    """


class WikimediaEventStreamMeta6(BaseModel):
    domain: Annotated[str | None, Field(min_length=1)] = None
    """
    Domain the event or entity pertains to
    """

    dt: Annotated[AwareDatetime, Field(max_length=128)]
    """
    UTC event datetime, in ISO-8601 format
    """

    id: str | None = None
    """
    Unique ID of this event
    """

    request_id: str | None = None
    """
    Unique ID of the request that caused the event
    """

    stream: Annotated[str, Field(min_length=1)]
    """
    Name of the stream/queue/dataset that this event belongs in
    """

    uri: Annotated[str | None, Field(max_length=8192)] = None
    """
    Unique URI identifying the event or entity
    """


class WikimediaEventStreamNewRedirectPage(BaseModel):
    """
    Information about the new redirect page auto-created at the old title as a result of this page move. This field is optional and will be absent if no redirect page was created.

    """

    page_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    """
    The page ID of the newly created redirect page.
    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    This will be the same as prior_state.page_namespace.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    This will be the same as prior_state.page_title.
    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The revision created for the newly created redirect page.
    """


class WikimediaEventStreamOperation(Enum):
    """
    Type of update received:
      * diff: only the required set of triples to add or remove is present in
        the message
      * import: all the entity triples are present
      * delete: the entity has been deleted from the wikibase instance, no
        RDF data is passed, the consumer must know how to delete the triples
        related to this entity
      * reconcile: indication that prior inconsistencies might have been
        detected and that the data consumed so far for this entity cannot be
        trusted, all the entity data is provided and a full reconciliation
        must happen.

    """

    diff = "diff"
    import_ = "import"
    delete = "delete"
    reconcile = "reconcile"


class WikimediaEventStreamPage(BaseModel):
    """
    Fields for MediaWiki page entity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    is_redirect: bool | None = None
    """
    True if the page is a redirect page at the time of this event.
    """

    namespace_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The id of the namespace this page belongs to.
    """

    page_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) page ID of the page.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page.
    """

    redirect_page_link: Annotated[
        WikimediaEventStreamRedirectPageLink | None,
        Field(
            examples=[
                {
                    "interwiki_prefix": "dolor",
                    "is_redirect": False,
                    "namespace_id": 1351079888211148,
                    "page_id": 1351079888211148,
                    "page_title": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/page_link",
        ),
    ] = None
    """
    If this page is currently a redirect, then this field contains information about the target page the redirect links to.


    Example: {'interwiki_prefix': 'dolor', 'is_redirect': False, 'namespace_id': 1351079888211148, 'page_id': 1351079888211148, 'page_title': 'dolor'}
    """

    revision_count: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The number of revisions of this page at the time of this event. During a delete, this number of revisions will be archived. This field is likely only set for page delete events, as getting this information on all events is expensive.

    """


class WikimediaEventStreamPage1(BaseModel):
    """
    Fields for MediaWiki page entity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    is_redirect: bool | None = None
    """
    True if the page is a redirect page at the time of this event.
    """

    namespace_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The id of the namespace this page belongs to.
    """

    page_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The (database) page ID of the page.
    """

    page_title: Annotated[str | None, Field(min_length=1)] = None
    """
    The normalized title of the page.
    """

    revision_count: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    NOTE: prior_state.page.revision_count is unlikely to be set, as getting the # of revisions previous to this change is difficult. This field is present here for backwards compatibiliy.

    """


class WikimediaEventStreamPageChangeKind(Enum):
    """
    The origin kind of the change to this page as viewed by MediaWiki.

    """

    create = "create"
    undelete = "undelete"
    edit = "edit"
    move = "move"
    delete = "delete"
    visibility_change = "visibility_change"


class WikimediaEventStreamPerformer(BaseModel):
    """
    Represents the user that performed this change.
    """

    user_edit_count: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The number of edits this user has made at the time of this event. Not present for anonymous users.

    """

    user_groups: list[WikimediaEventStreamUserGroup] | None = None
    """
    A list of the groups this user belongs to.  E.g. bot, sysop etc.
    """

    user_id: Annotated[int | None, Field(ge=-9007199254740991, le=9007199254740991)] = (
        None
    )
    """
    The user id that performed this change.  This is optional, and will not be present for anonymous users.

    """

    user_is_bot: bool | None = None
    """
    True if this user is considered to be a bot at the time of this event. This is checked via the $user->isBot() method, which considers both user_groups and user permissions.

    """

    user_registration_dt: Annotated[AwareDatetime | None, Field(max_length=128)] = None
    """
    The datetime of the user account registration. Not present for anonymous users or if missing in the MW database.

    """

    user_text: Annotated[str | None, Field(min_length=1)] = None
    """
    The text representation of the user that performed this change.
    """


class WikimediaEventStreamPerformer12(BaseModel):
    """
    Represents the MediaWiki actor that made this change. If this change is an edit, this will be the same as revision.editor.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    edit_count: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The number of edits this user has made at the time of this event. Not present for anonymous users.

    """

    groups: list[WikimediaEventStreamUserGroup] | None = None
    """
    A list of the groups this user belongs to.  E.g. bot, sysop etc. Not present for anonymous users.

    """

    is_bot: bool | None = None
    """
    True if this user is considered to be a bot at the time of this event. This is checked via the $user->isBot() method, which considers both user_groups and user permissions.

    """

    is_system: bool | None = None
    """
    True if the user is a MediaWiki 'system' user. These are users that cannot 'authenticate'.  These are usually listed in ReservedUsernames.

    """

    is_temp: bool | None = None
    """
    True if the user is an autocreated temporary MediaWiki user. This is used for IP masking.

    """

    registration_dt: Annotated[AwareDatetime | None, Field(max_length=128)] = None
    """
    The datetime of the user account registration. Not present for anonymous users or if missing in the MW database.

    """

    user_central_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    Global cross-wiki user ID. See: https://www.mediawiki.org/wiki/Manual:Central_ID

    """

    user_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    MediaWiki User ID. This is optional, and will not be present for anonymous users.

    """

    user_text: Annotated[str | None, Field(min_length=1)] = None
    """
    The user name or text representation of the user that performed this change.

    """


class WikimediaEventStreamPerformer2(BaseModel):
    """
    Represents the user that performed this change.
    """

    user_edit_count: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The number of edits this user has made at the time of this event. Not present for anonymous users.

    """

    user_groups: list[WikimediaEventStreamUserGroup]
    """
    A list of the groups this user belongs to.  E.g. bot, sysop etc.
    """

    user_id: Annotated[int | None, Field(ge=-9007199254740991, le=9007199254740991)] = (
        None
    )
    """
    The user id that performed this change.  This is optional, and will not be present for anonymous users.

    """

    user_is_bot: bool
    """
    True if this user is considered to be a bot at the time of this event. This is checked via the $user->isBot() method, which considers both user_groups and user permissions.

    """

    user_registration_dt: Annotated[AwareDatetime | None, Field(max_length=128)] = None
    """
    The datetime of the user account registration. Not present for anonymous users or if missing in the MW database.

    """

    user_text: Annotated[str, Field(min_length=1)]
    """
    The text representation of the user that performed this change.
    """


class WikimediaEventStreamPredictedClassification(BaseModel):
    model_name: str
    """
    The name of the classsification model used.
    """

    model_version: str
    """
    The version of the classsification model used.
    """

    predictions: list[str]
    """
    A list of predictions made by this model.
    """

    probabilities: dict[str, float]
    """
    A list of probabilities made by this model. Each element is a key/value with class name and associated [0-1] probability.

    """


class WikimediaEventStreamPriorState(BaseModel):
    """
    The prior state of the entity before this event. If a top level entity field is not present in this object, then its value has not changed since the prior event.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace ID this page belonged to before this event.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of this page before this event.
    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The head revision of this page before this event.
    """


class WikimediaEventStreamPriorState10(BaseModel):
    """
    The prior state of the entity before this event.  Revisions always have visibility settings, so this object will always contain the visibility settings for the revision before this event.

    """

    visibility: WikimediaEventStreamVisibility | None = None
    """
    The prior visiblity state of this revision.
    """


class WikimediaEventStreamPriorState2(BaseModel):
    """
    The prior state of the entity before this event. If a top level entity field is not present in this object, then its value has not changed since the prior event.  If prior_state itself is not present, then this event had no relevant prior state, indicating that it is probably the first time this type has been emitted for this entity. For page undeletes, prior_state will be absent unless the page_id is no longer the same as the page_id it had before it was deleted.

    """

    page_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    """
    The page ID before this restore as it was in the archive table.
    """


class WikimediaEventStreamPriorState4(BaseModel):
    """
    Prior state of this page before this event. Fields are only present if their values have changed.

    """

    page: Annotated[
        WikimediaEventStreamPage1 | None,
        Field(
            examples=[
                {
                    "is_redirect": False,
                    "namespace_id": 1351079888211148,
                    "page_id": 1351079888211148,
                    "page_title": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/page",
        ),
    ] = None
    """
    Fields for MediaWiki page entity.

    Example: {'is_redirect': False, 'namespace_id': 1351079888211148, 'page_id': 1351079888211148, 'page_title': 'dolor'}
    """

    revision: Annotated[
        WikimediaEventStreamRevision | None,
        Field(
            examples=[
                {
                    "comment": "dolor",
                    "editor": {
                        "edit_count": 1351079888211148,
                        "groups": ["dolor"],
                        "is_bot": False,
                        "is_system": False,
                        "is_temp": False,
                        "registration_dt": "2021-01-01T00:00:00.0Z",
                        "user_central_id": 1351079888211148,
                        "user_id": 1351079888211148,
                        "user_text": "dolor",
                    },
                    "is_comment_visible": False,
                    "is_content_visible": False,
                    "is_editor_visible": False,
                    "is_minor_edit": False,
                    "rev_dt": "2021-01-01T00:00:00.0Z",
                    "rev_id": 1351079888211149,
                    "rev_parent_id": 1351079888211148,
                    "rev_sha1": "dolor",
                    "rev_size": 1351079888211148,
                }
            ],
            title="fragment/mediawiki/state/entity/revision",
        ),
    ] = None
    """
    Fields for MediaWiki revision entity.

    Example: {'comment': 'dolor', 'editor': {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}, 'is_comment_visible': False, 'is_content_visible': False, 'is_editor_visible': False, 'is_minor_edit': False, 'rev_dt': '2021-01-01T00:00:00.0Z', 'rev_id': 1351079888211149, 'rev_parent_id': 1351079888211148, 'rev_sha1': 'dolor', 'rev_size': 1351079888211148}
    """


class WikimediaEventStreamPriorState6(BaseModel):
    """
    Prior state of this page before this event. Fields are only present if their values have changed.

    """

    page: Annotated[
        WikimediaEventStreamPage1 | None,
        Field(
            examples=[
                {
                    "is_redirect": False,
                    "namespace_id": 1351079888211148,
                    "page_id": 1351079888211148,
                    "page_title": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/page",
        ),
    ] = None
    """
    Fields for MediaWiki page entity.

    Example: {'is_redirect': False, 'namespace_id': 1351079888211148, 'page_id': 1351079888211148, 'page_title': 'dolor'}
    """

    revision: Annotated[
        WikimediaEventStreamRevision4 | None,
        Field(
            examples=[
                {
                    "comment": "dolor",
                    "editor": {
                        "edit_count": 1351079888211148,
                        "groups": ["dolor"],
                        "is_bot": False,
                        "is_system": False,
                        "is_temp": False,
                        "registration_dt": "2021-01-01T00:00:00.0Z",
                        "user_central_id": 1351079888211148,
                        "user_id": 1351079888211148,
                        "user_text": "dolor",
                    },
                    "is_comment_visible": False,
                    "is_content_visible": False,
                    "is_editor_visible": False,
                    "is_minor_edit": False,
                    "rev_dt": "2021-01-01T00:00:00.0Z",
                    "rev_id": 1351079888211149,
                    "rev_parent_id": 1351079888211148,
                    "rev_sha1": "dolor",
                    "rev_size": 1351079888211148,
                }
            ],
            title="fragment/mediawiki/state/entity/revision",
        ),
    ] = None
    """
    Fields for MediaWiki revision entity.

    Example: {'comment': 'dolor', 'editor': {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}, 'is_comment_visible': False, 'is_content_visible': False, 'is_editor_visible': False, 'is_minor_edit': False, 'rev_dt': '2021-01-01T00:00:00.0Z', 'rev_id': 1351079888211149, 'rev_parent_id': 1351079888211148, 'rev_sha1': 'dolor', 'rev_size': 1351079888211148}
    """


class WikimediaEventStreamPriorState8(BaseModel):
    """
    The prior state of the entity before this event. If the field is not present, the revision has no tags before the event has happened.

    """

    tags: list[str] | None = None
    """
    The list of tags before the event has happened.
    """


class WikimediaEventStreamRdfAddedData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: str
    """
    the RDF data encoded using mime_type
    """

    mime_type: str
    """
    Mime type of the RDF data stored in the data field
    """


class WikimediaEventStreamRedirectPageLink(BaseModel):
    """
    If this page is currently a redirect, then this field contains information about the target page the redirect links to.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    interwiki_prefix: str | None = None
    """
    The interwiki prefix (iw_prefix) of this link. The presence of this prefix implies a target outside the local wiki. See https://meta.wikimedia.org/wiki/Help:Interwiki_linking

    """

    is_redirect: bool | None = None
    """
    True if the page is a redirect page at the time of this event.
    """

    namespace_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The id of the namespace this page belongs to.
    """

    page_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The (database) page ID of the page.
    """

    page_title: Annotated[str | None, Field(min_length=1)] = None
    """
    The normalized title of the page.
    """


class WikimediaEventStreamRemovedLink(BaseModel):
    external: bool | None = None
    """
    Whether link is external
    """

    link: str | None = None
    """
    Link being removed
    """


class WikimediaEventStreamRevRevertDetails(BaseModel):
    """
    Details about the revert.
    """

    rev_is_exact_revert: bool
    """
    Flag indicating whether the revert was exact, i.e. the contents of the revert revision and restored revision match.

    """

    rev_original_rev_id: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None
    """
    The ID of an earlier revision that is being repeated or restored.

    """

    rev_revert_method: WikimediaEventStreamRevRevertMethod
    """
    The method that was used to perform the revert.
    """

    rev_reverted_revs: list[WikimediaEventStreamRevRevertedRev]
    """
    IDs of revisions that were reverted by this edit, ordered from oldest to newest.

    """


class WikimediaEventStreamRevRevertMethod(Enum):
    """
    The method that was used to perform the revert.
    """

    rollback = "rollback"
    undo = "undo"
    manual = "manual"


class WikimediaEventStreamRevRevertedRev(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class WikimediaEventStreamRevSlots(BaseModel):
    """
    The revision slots attached to this revision.

    """

    main: Annotated[
        WikimediaEventStreamMain,
        Field(
            examples=[
                {
                    "rev_slot_content_model": "dolor",
                    "rev_slot_origin_rev_id": 1351079888211148,
                    "rev_slot_sha1": "dolor",
                    "rev_slot_size": 1351079888211148,
                }
            ],
            title="fragment/mediawiki/revision/slot",
        ),
    ]
    """
    Schema fields describing a revision slot

    Example: {'rev_slot_content_model': 'dolor', 'rev_slot_origin_rev_id': 1351079888211148, 'rev_slot_sha1': 'dolor', 'rev_slot_size': 1351079888211148}
    """


class WikimediaEventStreamRevision(BaseModel):
    """
    Fields for MediaWiki revision entity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    comment: str | None = None
    """
    The comment left by the editor when this revision was made.
    """

    content_slots: Annotated[
        dict[str, WikimediaEventStreamContentSlots] | None,
        Field(
            examples=[
                {
                    "dolorb": {
                        "content_body": "dolor",
                        "content_format": "dolor",
                        "content_model": "dolor",
                        "content_sha1": "dolor",
                        "content_size": 1351079888211148,
                        "origin_rev_id": 1351079888211148,
                        "slot_role": "dolor",
                    }
                }
            ],
            title="fragment/mediawiki/state/entity/revision_slots",
        ),
    ] = None
    """
    Map type representing MediaWiki's revision content slots. This map is keyed by the slot role name, e.g. 'main'.


    Example: {'dolorb': {'content_body': 'dolor', 'content_format': 'dolor', 'content_model': 'dolor', 'content_sha1': 'dolor', 'content_size': 1351079888211148, 'origin_rev_id': 1351079888211148, 'slot_role': 'dolor'}}
    """

    editor: Annotated[
        WikimediaEventStreamEditor | None,
        Field(
            examples=[
                {
                    "edit_count": 1351079888211148,
                    "groups": ["dolor"],
                    "is_bot": False,
                    "is_system": False,
                    "is_temp": False,
                    "registration_dt": "2021-01-01T00:00:00.0Z",
                    "user_central_id": 1351079888211148,
                    "user_id": 1351079888211148,
                    "user_text": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/user",
        ),
    ] = None
    """
    Represents the MediaWiki user that made this edit.

    Example: {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}
    """

    is_comment_visible: bool | None = None
    """
    Whether the comment of the revision is visible. See RevisionRecord->DELETED_COMMENT.

    """

    is_content_visible: bool | None = None
    """
    Whether the revision's content body is visible. If this is false, then content should be redacted. See RevisionRecord->DELETED_TEXT

    """

    is_editor_visible: bool | None = None
    """
    Whether the revision's editor information is visible. Affects editor field. See RevisionRecord->DELETED_USER

    """

    is_minor_edit: bool | None = None
    """
    True if the editor marked this revision as a minor edit.
    """

    rev_dt: Annotated[AwareDatetime | None, Field(max_length=128)] = None
    """
    Time this revision was created. This is rev_timestamp in the MediaWiki database.

    """

    rev_id: Annotated[int | None, Field(ge=1, le=9007199254740991)] = None
    """
    The (database) revision ID.
    """

    rev_parent_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    This revision's parent rev_id.
    """

    rev_sha1: str | None = None
    """
    sha1 sum considering all the content slots for this revision.

    """

    rev_size: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    Byte size 'sum' of all the content slots for this revision. This 'size' is approximate, but may not be exact, depending on the kind of data that is stored in the content slots.

    """


class WikimediaEventStreamRevision1(BaseModel):
    """
    Fields for MediaWiki revision entity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    comment: str | None = None
    """
    The comment left by the editor when this revision was made.
    """

    content_slots: Annotated[
        dict[str, WikimediaEventStreamContentSlots] | None,
        Field(
            examples=[
                {
                    "dolorb": {
                        "content_body": "dolor",
                        "content_format": "dolor",
                        "content_model": "dolor",
                        "content_sha1": "dolor",
                        "content_size": 1351079888211148,
                        "origin_rev_id": 1351079888211148,
                        "slot_role": "dolor",
                    }
                }
            ],
            title="fragment/mediawiki/state/entity/revision_slots",
        ),
    ] = None
    """
    Map type representing MediaWiki's revision content slots. This map is keyed by the slot role name, e.g. 'main'.


    Example: {'dolorb': {'content_body': 'dolor', 'content_format': 'dolor', 'content_model': 'dolor', 'content_sha1': 'dolor', 'content_size': 1351079888211148, 'origin_rev_id': 1351079888211148, 'slot_role': 'dolor'}}
    """

    editor: Annotated[
        WikimediaEventStreamEditor | None,
        Field(
            examples=[
                {
                    "edit_count": 1351079888211148,
                    "groups": ["dolor"],
                    "is_bot": False,
                    "is_system": False,
                    "is_temp": False,
                    "registration_dt": "2021-01-01T00:00:00.0Z",
                    "user_central_id": 1351079888211148,
                    "user_id": 1351079888211148,
                    "user_text": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/user",
        ),
    ] = None
    """
    Represents the MediaWiki user that made this edit.

    Example: {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}
    """

    is_comment_visible: bool | None = None
    """
    Whether the comment of the revision is visible. See RevisionRecord->DELETED_COMMENT.

    """

    is_content_visible: bool | None = None
    """
    Whether the revision's content body is visible. If this is false, then content should be redacted. See RevisionRecord->DELETED_TEXT

    """

    is_editor_visible: bool | None = None
    """
    Whether the revision's editor information is visible. Affects editor field. See RevisionRecord->DELETED_USER

    """

    is_minor_edit: bool | None = None
    """
    True if the editor marked this revision as a minor edit.
    """

    rev_dt: Annotated[AwareDatetime, Field(max_length=128)]
    """
    Time this revision was created. This is rev_timestamp in the MediaWiki database.

    """

    rev_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    """
    The (database) revision ID.
    """

    rev_parent_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    This revision's parent rev_id.
    """

    rev_sha1: str | None = None
    """
    sha1 sum considering all the content slots for this revision.

    """

    rev_size: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    Byte size 'sum' of all the content slots for this revision. This 'size' is approximate, but may not be exact, depending on the kind of data that is stored in the content slots.

    """


class WikimediaEventStreamRevision4(BaseModel):
    """
    Fields for MediaWiki revision entity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    comment: str | None = None
    """
    The comment left by the editor when this revision was made.
    """

    editor: Annotated[
        WikimediaEventStreamEditor | None,
        Field(
            examples=[
                {
                    "edit_count": 1351079888211148,
                    "groups": ["dolor"],
                    "is_bot": False,
                    "is_system": False,
                    "is_temp": False,
                    "registration_dt": "2021-01-01T00:00:00.0Z",
                    "user_central_id": 1351079888211148,
                    "user_id": 1351079888211148,
                    "user_text": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/user",
        ),
    ] = None
    """
    Represents the MediaWiki user that made this edit.

    Example: {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}
    """

    is_comment_visible: bool | None = None
    """
    Whether the comment of the revision is visible. See RevisionRecord->DELETED_COMMENT.

    """

    is_content_visible: bool | None = None
    """
    Whether the revision's content body is visible. If this is false, then content should be redacted. See RevisionRecord->DELETED_TEXT

    """

    is_editor_visible: bool | None = None
    """
    Whether the revision's editor information is visible. Affects editor field. See RevisionRecord->DELETED_USER

    """

    is_minor_edit: bool | None = None
    """
    True if the editor marked this revision as a minor edit.
    """

    rev_dt: Annotated[AwareDatetime | None, Field(max_length=128)] = None
    """
    Time this revision was created. This is rev_timestamp in the MediaWiki database.

    """

    rev_id: Annotated[int | None, Field(ge=1, le=9007199254740991)] = None
    """
    The (database) revision ID.
    """

    rev_parent_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    This revision's parent rev_id.
    """

    rev_sha1: str | None = None
    """
    sha1 sum considering all the content slots for this revision.

    """

    rev_size: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    Byte size 'sum' of all the content slots for this revision. This 'size' is approximate, but may not be exact, depending on the kind of data that is stored in the content slots.

    """


class WikimediaEventStreamRevision5(BaseModel):
    """
    Fields for MediaWiki revision entity.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    comment: str | None = None
    """
    The comment left by the editor when this revision was made.
    """

    editor: Annotated[
        WikimediaEventStreamEditor | None,
        Field(
            examples=[
                {
                    "edit_count": 1351079888211148,
                    "groups": ["dolor"],
                    "is_bot": False,
                    "is_system": False,
                    "is_temp": False,
                    "registration_dt": "2021-01-01T00:00:00.0Z",
                    "user_central_id": 1351079888211148,
                    "user_id": 1351079888211148,
                    "user_text": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/user",
        ),
    ] = None
    """
    Represents the MediaWiki user that made this edit.

    Example: {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}
    """

    is_comment_visible: bool | None = None
    """
    Whether the comment of the revision is visible. See RevisionRecord->DELETED_COMMENT.

    """

    is_content_visible: bool | None = None
    """
    Whether the revision's content body is visible. If this is false, then content should be redacted. See RevisionRecord->DELETED_TEXT

    """

    is_editor_visible: bool | None = None
    """
    Whether the revision's editor information is visible. Affects editor field. See RevisionRecord->DELETED_USER

    """

    is_minor_edit: bool | None = None
    """
    True if the editor marked this revision as a minor edit.
    """

    rev_dt: Annotated[AwareDatetime, Field(max_length=128)]
    """
    Time this revision was created. This is rev_timestamp in the MediaWiki database.

    """

    rev_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    """
    The (database) revision ID.
    """

    rev_parent_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    This revision's parent rev_id.
    """

    rev_sha1: str | None = None
    """
    sha1 sum considering all the content slots for this revision.

    """

    rev_size: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    Byte size 'sum' of all the content slots for this revision. This 'size' is approximate, but may not be exact, depending on the kind of data that is stored in the content slots.

    """


class WikimediaEventStreamRevision8(BaseModel):
    """
    Old and new revision IDs
    """

    new: int | None = None
    """
    (rc_last_oldid)
    """

    old: int | None = None
    """
    (rc_this_oldid)
    """


class WikimediaEventStreamUserGroup(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class WikimediaEventStreamV2StreamEventgateMainTestEventGetResponse(BaseModel):
    """
    Schema used for simple tests
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    dt: Annotated[AwareDatetime, Field(max_length=128)]
    """
    ISO-8601 formatted timestamp of when the event occurred/was generated in UTC), AKA 'event time'. This is different than meta.dt, which is used as the time the system received this event.

    """

    meta: WikimediaEventStreamMeta
    test: str = "default value"
    test_int: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None
    test_map: dict[str, str] | None = None
    """
    We want to support 'map' types using additionalProperties to specify the value types.  (Keys are always strings.)

    """


class WikimediaEventStreamV2StreamMediainfoStreamingUpdaterMutationV2GetResponse(
    BaseModel
):
    """
    Schema representing a change in the RDF structure of a Wikibase entity.
    The RDF representation conforms to the
    https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format
    with the variations required by WDQS:
      * rdf:type statements are omitted for performance reasons
      * data (wdata:) nodes are not emitted
      * only rdfs:label is present (duplicated schema:name & skos:prefLabel are
        omitted)
      * SomeValue are not encoded as blank node but skolems
        (https://www.mediawiki.org/wiki/Wikidata_Query_Service/Blank_Node_Skolemization)

    The event may happen for different reasons but in most cases it is because of
    change happening to the wikibase entity. For these cases the operation
    field is set to:
      * import: when an entity is created or restored
      * diff: when an entity is edited (new revision)
      * delete: when an entity is deleted

    In some rarer cases the event may happen for operational purposes when some
    inconsistencies have been discovered. For these cases the operation field
    may be set to:
      * reconcile: to tell the consumer that prior data it received concerning
        this entity might no longer be trusted and that it should consider using
        the data provided by this event.
      * delete: may also happen for similar purposes when the system discovers
        that possibly prior events may have wrongly instructed consumers to keep
        the data related to this entity while in fact it no longer exists.

    The purpose of this schema is to be self-sufficient to keep an RDF
    representation of a Wikibase instance up-to-date (i.e. a triple store) and
    thus contains all the necessary data to do so without having to call any
    Wikibase API.

    The RDF data itself is encoded in 4 fields:
      * rdf_added_data: the triples that must be added
      * rdf_deleted_data: the triples that must be deleted
      * rdf_linked_shared_data: the triples that might be shared by other
        entities and could be added. The stream is not aware if this data has
        already been transferred and thus adding this data again might not be
        necessary.
      * rdf_unlinked_shared_data: triples that might be used by other entities
        but are no longer linked from this entity.  It is up to the client to
        determine if these triples are worth keeping or not. Keeping them might
        lead to "orphaned" triples in the graph. A client may decide that
        orphans in the graph are an acceptable trade-off or may decide to treat
        them by deleting them on the fly if they are no longer used.
        This generally includes:
          * complex values
          * references
          * site links

    The RDF data is encoded using the format defined in the mime_type field. As
    of now only "text/turtle" is expected to be produced. It may be possible
    that other formats will be used if they're proven more space efficient.

    These data fields are populated differently depending on the type operation
    performed:
      * import: rdf_added_data and rdf_linked_shared_data are populated
      * diff: all these four fields are populated
      * delete: none of them, the client must be able to retrieve all the
        related triples owned by the given entity.
      * reconcile: only rdf_added_data is used

    The event may be stored in messaging system that may not be designed to
    store large payloads (i.e. kafka). Since the data of a wikibase entity may
    possibly be large comparatively to what is acceptable by such messaging
    system the event may be split into multiple consecutive chunks.
    Event that are split are identified using the two fields:
      * sequence: the index of the chunk, starting from 0
      * sequence_length: the number of chunks the event was split into
    The client must reconstruct the message before processing it. Chunks
    related to the same event will have the same data in all its fields except
    for:
      * the fields containing the rdf content
      * the meta.dt field
      * the meta.id field
    To reconstruct the event the client must parse the content of all the
    individual rdf content fields into a list of rdf statements and append to
    these lists the statement it parses for all the chunks.
    When consuming from a stream chunks are expected to appear consecutively,
    the meta.request_id can be used to verify that the chunks are consistent.
    When consuming from a stream the client must be able to buffer all the chunks
    for a given event but is not required to buffer multiple events. In other
    words a stream consumer can simply buffer event testing the simple condition:
      * sequence + 1 == sequence_length.
    When using this data from a batch storage client is expected to reconstruct
    the event grouping on meta.request_id for messages having sequence_length > 1.

    Messages ordering in the stream:
      * two consecutive edits happening on the same entity are guaranteed to
        appear one after another in the right order
      * two consecutive edits happening on two different entities are not
        guaranteed to appear in the same order they happened in the wikibase
        instance
    This is generally not a problem but may pose interesting challenges for
    sitelinks which are currently modeled as a separate "well identified" subject.
    In other words this means that two entities might possibly link to the same
    sitelink while the stream is consumed.
    This is one of the reason the site links portion of the graph is considered
    "shared linked data". The other reason is historical, see T44325.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    dt: Annotated[AwareDatetime, Field(max_length=128)]
    """
    ISO-8601 formatted timestamp of when the event occurred/was generated in UTC), AKA 'event time'. This is different than meta.dt, which is used as the time the system received this event.

    """

    entity_id: str
    """
    Wikibase entity ID being modified
    """

    meta: WikimediaEventStreamMeta
    operation: WikimediaEventStreamOperation
    """
    Type of update received:
      * diff: only the required set of triples to add or remove is present in
        the message
      * import: all the entity triples are present
      * delete: the entity has been deleted from the wikibase instance, no
        RDF data is passed, the consumer must know how to delete the triples
        related to this entity
      * reconcile: indication that prior inconsistencies might have been
        detected and that the data consumed so far for this entity cannot be
        trusted, all the entity data is provided and a full reconciliation
        must happen.

    """

    rdf_added_data: WikimediaEventStreamRdfAddedData | None = None
    rdf_deleted_data: WikimediaEventStreamRdfAddedData | None = None
    rdf_linked_shared_data: WikimediaEventStreamRdfAddedData | None = None
    rdf_unlinked_shared_data: WikimediaEventStreamRdfAddedData | None = None
    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) revision ID related to this change.
    """

    sequence: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The sequence number of this message used to reconstruct the event when it was considered too large to be encoded as a single message. The number of messages is encoded in sequence_length.

    """

    sequence_length: Annotated[int, Field(ge=1, le=9007199254740991)]
    """
    The number of messages that have to be read to reconstruct this message.

    """


class WikimediaEventStreamV2StreamMediawikiPageChangeV1GetResponse(BaseModel):
    """
    Represents a MediaWiki page state change in a changelog. This event models all state changes to MediaWiki pages. It supersedes the other page and revision based event models. See: https://phabricator.wikimedia.org/T308017

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    changelog_kind: WikimediaEventStreamChangelogKind
    """
    The kind of this event in a changelog. This is used to map the event to an action in a data store.

    """

    comment: str | None = None
    """
    The comment left by the user that performed this change. Same as revision.comment on edits.

    """

    created_redirect_page: Annotated[
        WikimediaEventStreamCreatedRedirectPage | None,
        Field(
            examples=[
                {
                    "is_redirect": False,
                    "namespace_id": 1351079888211148,
                    "page_id": 1351079888211148,
                    "page_title": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/page",
        ),
    ] = None
    """
    Page entity that was created at the old title during a page move. This is only set for page move events. Note that the created_redirect_page will also have its own associated page create event.


    Example: {'is_redirect': False, 'namespace_id': 1351079888211148, 'page_id': 1351079888211148, 'page_title': 'dolor'}
    """

    dt: Annotated[AwareDatetime, Field(max_length=128)]
    """
    ISO-8601 formatted timestamp of when the event occurred/was generated in UTC), AKA 'event time'. This is different than meta.dt, which is used as the time the system received this event.

    """

    meta: WikimediaEventStreamMeta
    page: Annotated[
        WikimediaEventStreamPage,
        Field(
            examples=[
                {
                    "is_redirect": False,
                    "namespace_id": 1351079888211148,
                    "page_id": 1351079888211148,
                    "page_title": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/page",
        ),
    ]
    """
    Fields for MediaWiki page entity.

    Example: {'is_redirect': False, 'namespace_id': 1351079888211148, 'page_id': 1351079888211148, 'page_title': 'dolor'}
    """

    page_change_kind: WikimediaEventStreamPageChangeKind
    """
    The origin kind of the change to this page as viewed by MediaWiki.

    """

    performer: Annotated[
        WikimediaEventStreamPerformer12 | None,
        Field(
            examples=[
                {
                    "edit_count": 1351079888211148,
                    "groups": ["dolor"],
                    "is_bot": False,
                    "is_system": False,
                    "is_temp": False,
                    "registration_dt": "2021-01-01T00:00:00.0Z",
                    "user_central_id": 1351079888211148,
                    "user_id": 1351079888211148,
                    "user_text": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/user",
        ),
    ] = None
    """
    Represents the MediaWiki actor that made this change. If this change is an edit, this will be the same as revision.editor.


    Example: {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}
    """

    prior_state: WikimediaEventStreamPriorState4 | None = None
    """
    Prior state of this page before this event. Fields are only present if their values have changed.

    """

    revision: Annotated[
        WikimediaEventStreamRevision1,
        Field(
            examples=[
                {
                    "comment": "dolor",
                    "editor": {
                        "edit_count": 1351079888211148,
                        "groups": ["dolor"],
                        "is_bot": False,
                        "is_system": False,
                        "is_temp": False,
                        "registration_dt": "2021-01-01T00:00:00.0Z",
                        "user_central_id": 1351079888211148,
                        "user_id": 1351079888211148,
                        "user_text": "dolor",
                    },
                    "is_comment_visible": False,
                    "is_content_visible": False,
                    "is_editor_visible": False,
                    "is_minor_edit": False,
                    "rev_dt": "2021-01-01T00:00:00.0Z",
                    "rev_id": 1351079888211149,
                    "rev_parent_id": 1351079888211148,
                    "rev_sha1": "dolor",
                    "rev_size": 1351079888211148,
                }
            ],
            title="fragment/mediawiki/state/entity/revision",
        ),
    ]
    """
    Fields for MediaWiki revision entity.

    Example: {'comment': 'dolor', 'editor': {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}, 'is_comment_visible': False, 'is_content_visible': False, 'is_editor_visible': False, 'is_minor_edit': False, 'rev_dt': '2021-01-01T00:00:00.0Z', 'rev_id': 1351079888211149, 'rev_parent_id': 1351079888211148, 'rev_sha1': 'dolor', 'rev_size': 1351079888211148}
    """

    wiki_id: Annotated[str, Field(min_length=1)]
    """
    The wiki ID, which is usually the same as the MediaWiki database name. E.g. enwiki, metawiki, etc.

    """


class WikimediaEventStreamV2StreamMediawikiPageCreateGetResponse(BaseModel):
    """
    Represents a MW Revision Create event.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    chronology_id: str | None = None
    """
    Deprecated - no longer populated
    """

    comment: str | None = None
    """
    The comment left by the user that performed this change.
    """

    database: Annotated[str, Field(min_length=1)]
    """
    The name of the wiki database this event entity belongs to.
    """

    dt: Annotated[AwareDatetime, Field(max_length=128)]
    """
    ISO-8601 formatted timestamp of when the event occurred/was generated in UTC), AKA 'event time'. This is different than meta.dt, which is used as the time the system received this event.

    """

    meta: WikimediaEventStreamMeta
    page_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    """
    The page ID of the page this revision belongs to.
    """

    page_is_redirect: bool
    """
    True if this revision is a redirect.  This fact is ultimately represented by revision content containing redirect wikitext.  If this revision is the head revision of the page, then the page will also be a redirect.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace of the page this revision belongs to.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page this revision belongs to.
    """

    parsedcomment: str | None = None
    """
    The comment left by the user that performed this change parsed into simple HTML. Optional

    """

    performer: WikimediaEventStreamPerformer | None = None
    """
    Represents the user that performed this change.
    """

    rev_content_changed: bool | None = None
    """
    True if the content has changed (rev_sha1 is different than the previous revision one)
    """

    rev_content_format: str | None = None
    """
    The content format of the revision.
    """

    rev_content_model: str | None = None
    """
    The content model of the revision.
    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) revision ID.
    """

    rev_is_revert: bool | None = None
    """
    Flag indicating whether the edit was a revert.
    """

    rev_len: Annotated[int | None, Field(ge=-9007199254740991, le=9007199254740991)] = (
        None
    )
    """
    The length of the revision text in bytes.
    """

    rev_minor_edit: bool | None = None
    """
    Flag identifying if the revision is minor.
    """

    rev_parent_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The parent revison ID of the revision that this event represents.
    """

    rev_revert_details: WikimediaEventStreamRevRevertDetails | None = None
    """
    Details about the revert.
    """

    rev_sha1: str | None = None
    """
    The sha1 of the revision text.
    """

    rev_slots: WikimediaEventStreamRevSlots | None = None
    """
    The revision slots attached to this revision.

    """

    rev_timestamp: Annotated[AwareDatetime, Field(max_length=128)]
    """
    The revision's creation time in ISO8601 format.  This field does not end in '_dt' to better match the field name on the Mediawiki revision table.

    """


class WikimediaEventStreamV2StreamMediawikiPageDeleteGetResponse(BaseModel):
    """
    Represents a MW Page Delete event.
    """

    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    chronology_id: str | None = None
    """
    Deprecated - no longer populated
    """

    comment: str | None = None
    """
    The comment left by the user that performed this change.
    """

    database: Annotated[str, Field(min_length=1)]
    """
    The name of the wiki database this event entity belongs to.
    """

    meta: WikimediaEventStreamMeta6
    page_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) page ID.
    """

    page_is_redirect: bool
    """
    True if this page is currently a redirect page.  This fact is ultimately represented by revision content containing redirect wikitext.  If rev_id's content has redirect wikitext, then this page is a redirect.  Note that this state is also stored on the Mediawiki page table.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace ID this page belongs to.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page.
    """

    parsedcomment: str | None = None
    """
    The comment left by the user that performed this change parsed into simple HTML. Optional

    """

    performer: WikimediaEventStreamPerformer2 | None = None
    """
    Represents the user that performed this change.
    """

    rev_count: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None
    """
    The number of revisions of this page at the time of this event. During a delete, this number of revisions will be archived.

    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The head revision of the page at the time of this event.
    """


class WikimediaEventStreamV2StreamMediawikiPageLinksChangeGetResponse(BaseModel):
    """
    Represents a MW Page Links Change event.
    """

    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    added_links: list[WikimediaEventStreamAddedLink] | None = None
    """
    The new page links. This map would only contain links that were either added or changed, links that were intact would not be present here. If the link was changed, its previous value would be present in the 'removed_links' object.

    """

    database: Annotated[str, Field(min_length=1)]
    """
    The name of the wiki database this event entity belongs to.
    """

    meta: WikimediaEventStreamMeta6
    page_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) page ID.
    """

    page_is_redirect: bool
    """
    True if this page is currently a redirect page.  This fact is ultimately represented by revision content containing redirect wikitext.  If rev_id's content has redirect wikitext, then this page is a redirect.  Note that this state is also stored on the Mediawiki page table.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace ID this page belongs to.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page.
    """

    performer: WikimediaEventStreamPerformer2 | None = None
    """
    Represents the user that performed this change.
    """

    removed_links: list[WikimediaEventStreamRemovedLink] | None = None
    """
    The old page links. This map would only contain the previous values of the links that were either removed or changed by this event. Links that were intact would not be present here. If the link was changed, its new value would be present in the 'added_links' object.

    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The head revision of the page at the time of this event.
    """


class WikimediaEventStreamV2StreamMediawikiPageMoveGetResponse(BaseModel):
    """
    Represents a MW Page Move event.
    """

    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    comment: Annotated[str | None, Field(min_length=1)] = None
    """
    The comment left by the user that performed this change.
    """

    database: Annotated[str, Field(min_length=1)]
    """
    The name of the wiki database this event entity belongs to.
    """

    meta: WikimediaEventStreamMeta6
    new_redirect_page: WikimediaEventStreamNewRedirectPage | None = None
    """
    Information about the new redirect page auto-created at the old title as a result of this page move. This field is optional and will be absent if no redirect page was created.

    """

    page_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) page ID.
    """

    page_is_redirect: bool
    """
    True if this page is currently a redirect page.  This fact is ultimately represented by revision content containing redirect wikitext.  If rev_id's content has redirect wikitext, then this page is a redirect.  Note that this state is also stored on the Mediawiki page table.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace ID this page belongs to.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page.
    """

    parsedcomment: str | None = None
    """
    The comment left by the user that performed this change parsed into simple HTML. Optional

    """

    performer: WikimediaEventStreamPerformer2 | None = None
    """
    Represents the user that performed this change.
    """

    prior_state: WikimediaEventStreamPriorState
    """
    The prior state of the entity before this event. If a top level entity field is not present in this object, then its value has not changed since the prior event.

    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The head revision of the page at the time of this event.
    """


class WikimediaEventStreamV2StreamMediawikiPagePropertiesChangeGetResponse(BaseModel):
    """
    Represents a MW Page Properties Change event.
    """

    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    added_properties: dict[str, Any] | None = None
    """
    The new page properties. This map would only contain properties that were either added or changed, properties that were intact would not be present here. If the property was changed, its previous value would be present in the 'removed_properties' object.

    """

    database: Annotated[str, Field(min_length=1)]
    """
    The name of the wiki database this event entity belongs to.
    """

    meta: WikimediaEventStreamMeta6
    page_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) page ID.
    """

    page_is_redirect: bool
    """
    True if this page is currently a redirect page.  This fact is ultimately represented by revision content containing redirect wikitext.  If rev_id's content has redirect wikitext, then this page is a redirect.  Note that this state is also stored on the Mediawiki page table.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace ID this page belongs to.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page.
    """

    performer: WikimediaEventStreamPerformer2 | None = None
    """
    Represents the user that performed this change.
    """

    removed_properties: dict[str, Any] | None = None
    """
    The old page properties. This map would only contain the previous values of the properties that were either removed or changed by this event. Properties that were intact would not be present here. If the property was changed, its new value would be present in the 'added_properties' object.

    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The head revision of the page at the time of this event.
    """


class WikimediaEventStreamV2StreamMediawikiPageRevertRiskPredictionChangeV1GetResponse(
    BaseModel
):
    """
    Represents a classification model output (topic, revert, quality, etc.). - topic model: https://meta.wikimedia.org/wiki/Machine_learning_models/Production/Language_agnostic_link-based_article_topic_model_card - quality model: https://meta.wikimedia.org/wiki/Machine_learning_models/Proposed/Language-agnostic_Wikipedia_article_quality_model_card

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    changelog_kind: WikimediaEventStreamChangelogKind
    """
    The kind of this event in a changelog. This is used to map the event to an action in a data store.

    """

    comment: str | None = None
    """
    The comment left by the user that performed this change. Same as revision.comment on edits.

    """

    created_redirect_page: Annotated[
        WikimediaEventStreamCreatedRedirectPage | None,
        Field(
            examples=[
                {
                    "is_redirect": False,
                    "namespace_id": 1351079888211148,
                    "page_id": 1351079888211148,
                    "page_title": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/page",
        ),
    ] = None
    """
    Page entity that was created at the old title during a page move. This is only set for page move events. Note that the created_redirect_page will also have its own associated page create event.


    Example: {'is_redirect': False, 'namespace_id': 1351079888211148, 'page_id': 1351079888211148, 'page_title': 'dolor'}
    """

    dt: Annotated[AwareDatetime, Field(max_length=128)]
    """
    ISO-8601 formatted timestamp of when the event occurred/was generated in UTC), AKA 'event time'. This is different than meta.dt, which is used as the time the system received this event.

    """

    meta: WikimediaEventStreamMeta
    page: Annotated[
        WikimediaEventStreamPage,
        Field(
            examples=[
                {
                    "is_redirect": False,
                    "namespace_id": 1351079888211148,
                    "page_id": 1351079888211148,
                    "page_title": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/page",
        ),
    ]
    """
    Fields for MediaWiki page entity.

    Example: {'is_redirect': False, 'namespace_id': 1351079888211148, 'page_id': 1351079888211148, 'page_title': 'dolor'}
    """

    page_change_kind: WikimediaEventStreamPageChangeKind
    """
    The origin kind of the change to this page as viewed by MediaWiki.

    """

    performer: Annotated[
        WikimediaEventStreamPerformer12 | None,
        Field(
            examples=[
                {
                    "edit_count": 1351079888211148,
                    "groups": ["dolor"],
                    "is_bot": False,
                    "is_system": False,
                    "is_temp": False,
                    "registration_dt": "2021-01-01T00:00:00.0Z",
                    "user_central_id": 1351079888211148,
                    "user_id": 1351079888211148,
                    "user_text": "dolor",
                }
            ],
            title="fragment/mediawiki/state/entity/user",
        ),
    ] = None
    """
    Represents the MediaWiki actor that made this change. If this change is an edit, this will be the same as revision.editor.


    Example: {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}
    """

    predicted_classification: WikimediaEventStreamPredictedClassification | None = None
    prior_state: WikimediaEventStreamPriorState6 | None = None
    """
    Prior state of this page before this event. Fields are only present if their values have changed.

    """

    revision: Annotated[
        WikimediaEventStreamRevision5,
        Field(
            examples=[
                {
                    "comment": "dolor",
                    "editor": {
                        "edit_count": 1351079888211148,
                        "groups": ["dolor"],
                        "is_bot": False,
                        "is_system": False,
                        "is_temp": False,
                        "registration_dt": "2021-01-01T00:00:00.0Z",
                        "user_central_id": 1351079888211148,
                        "user_id": 1351079888211148,
                        "user_text": "dolor",
                    },
                    "is_comment_visible": False,
                    "is_content_visible": False,
                    "is_editor_visible": False,
                    "is_minor_edit": False,
                    "rev_dt": "2021-01-01T00:00:00.0Z",
                    "rev_id": 1351079888211149,
                    "rev_parent_id": 1351079888211148,
                    "rev_sha1": "dolor",
                    "rev_size": 1351079888211148,
                }
            ],
            title="fragment/mediawiki/state/entity/revision",
        ),
    ]
    """
    Fields for MediaWiki revision entity.

    Example: {'comment': 'dolor', 'editor': {'edit_count': 1351079888211148, 'groups': ['dolor'], 'is_bot': False, 'is_system': False, 'is_temp': False, 'registration_dt': '2021-01-01T00:00:00.0Z', 'user_central_id': 1351079888211148, 'user_id': 1351079888211148, 'user_text': 'dolor'}, 'is_comment_visible': False, 'is_content_visible': False, 'is_editor_visible': False, 'is_minor_edit': False, 'rev_dt': '2021-01-01T00:00:00.0Z', 'rev_id': 1351079888211149, 'rev_parent_id': 1351079888211148, 'rev_sha1': 'dolor', 'rev_size': 1351079888211148}
    """

    wiki_id: Annotated[str, Field(min_length=1)]
    """
    The wiki ID, which is usually the same as the MediaWiki database name. E.g. enwiki, metawiki, etc.

    """


class WikimediaEventStreamV2StreamMediawikiPageUndeleteGetResponse(BaseModel):
    """
    Represents a MW Page Undelete (restore) event.
    """

    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    chronology_id: str | None = None
    """
    Deprecated - no longer populated
    """

    comment: str | None = None
    """
    The comment left by the user that performed this change.
    """

    database: Annotated[str, Field(min_length=1)]
    """
    The name of the wiki database this event entity belongs to.
    """

    meta: WikimediaEventStreamMeta6
    page_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) page ID.
    """

    page_is_redirect: bool
    """
    True if this page is currently a redirect page.  This fact is ultimately represented by revision content containing redirect wikitext.  If rev_id's content has redirect wikitext, then this page is a redirect.  Note that this state is also stored on the Mediawiki page table.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace ID this page belongs to.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page.
    """

    parsedcomment: str | None = None
    """
    The comment left by the user that performed this change parsed into simple HTML. Optional

    """

    performer: WikimediaEventStreamPerformer2 | None = None
    """
    Represents the user that performed this change.
    """

    prior_state: WikimediaEventStreamPriorState2 | None = None
    """
    The prior state of the entity before this event. If a top level entity field is not present in this object, then its value has not changed since the prior event.  If prior_state itself is not present, then this event had no relevant prior state, indicating that it is probably the first time this type has been emitted for this entity. For page undeletes, prior_state will be absent unless the page_id is no longer the same as the page_id it had before it was deleted.

    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The head revision of the page at the time of this event.
    """


class WikimediaEventStreamV2StreamMediawikiRecentchangeGetResponse(BaseModel):
    """
    Represents a MW RecentChange event. https://www.mediawiki.org/wiki/Manual:RCFeed

    """

    model_config = ConfigDict(
        extra="allow",
    )
    title: str | None = None
    """
    Full page name, from Title::getPrefixedText.
    """

    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    type: str | None = None
    """
    Type of recentchange event (rc_type). One of "edit", "new", "log", "categorize", or "external"; or a number. (See Manual:Recentchanges table#rc_type)

    """

    bot: bool | None = None
    """
    (rc_bot)
    """

    comment: str | None = None
    """
    (rc_comment)
    """

    id: int | None = None
    """
    ID of the recentchange event (rcid).
    """

    length: WikimediaEventStreamLength | None = None
    """
    Length of old and new change
    """

    log_action: str | None = None
    """
    (rc_log_action)
    """

    log_action_comment: str | None = None
    log_id: int | None = None
    """
    (rc_log_id)
    """

    log_params: Annotated[
        list[Any] | dict[str, Any] | str | None, Field(union_mode="smart")
    ] = None
    """
    Property only exists if event has rc_params.
    """

    log_type: str | None = None
    """
    (rc_log_type)
    """

    meta: WikimediaEventStreamMeta6
    minor: bool | None = None
    """
    (rc_minor).
    """

    namespace: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None
    """
    ID of relevant namespace of affected page (rc_namespace, page_namespace). This is -1 ("Special") for log events.

    """

    parsedcomment: str | None = None
    """
    The rc_comment parsed into simple HTML. Optional
    """

    patrolled: bool | None = None
    """
    (rc_patrolled). This property only exists if patrolling is supported for this event (based on $wgUseRCPatrol, $wgUseNPPatrol).

    """

    revision: WikimediaEventStreamRevision8 | None = None
    """
    Old and new revision IDs
    """

    server_name: str | None = None
    """
    $wgServerName
    """

    server_script_path: str | None = None
    """
    $wgScriptPath
    """

    server_url: str | None = None
    """
    $wgCanonicalServer
    """

    timestamp: Annotated[
        int | None, Field(ge=-9007199254740991, le=9007199254740991)
    ] = None
    """
    Unix timestamp (derived from rc_timestamp).
    """

    user: str | None = None
    """
    (rc_user_text)
    """

    wiki: str | None = None
    """
    wfWikiID ($wgDBprefix, $wgDBname)
    """


class WikimediaEventStreamV2StreamMediawikiRevisionTagsChangeGetResponse(BaseModel):
    """
    Represents a MW revision tags change event
    """

    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    chronology_id: str | None = None
    """
    Deprecated - no longer populated
    """

    comment: str | None = None
    """
    The comment left by the user that performed this change.
    """

    database: Annotated[str, Field(min_length=1)]
    """
    The name of the wiki database this event entity belongs to.
    """

    meta: WikimediaEventStreamMeta6
    page_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    """
    The page ID of the page this revision belongs to.
    """

    page_is_redirect: bool
    """
    True if this revision is a redirect.  This fact is ultimately represented by revision content containing redirect wikitext.  If this revision is the head revision of the page, then the page will also be a redirect.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace of the page this revision belongs to.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page this revision belongs to.
    """

    parsedcomment: str | None = None
    """
    The comment left by the user that performed this change parsed into simple HTML. Optional

    """

    performer: WikimediaEventStreamPerformer2 | None = None
    """
    Represents the user that performed this change.
    """

    prior_state: WikimediaEventStreamPriorState8 | None = None
    """
    The prior state of the entity before this event. If the field is not present, the revision has no tags before the event has happened.

    """

    rev_content_format: str | None = None
    """
    The content format of the revision.
    """

    rev_content_model: str | None = None
    """
    The content model of the revision.
    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) revision ID.
    """

    rev_len: Annotated[int | None, Field(ge=-9007199254740991, le=9007199254740991)] = (
        None
    )
    """
    The length of the revision text in bytes.
    """

    rev_minor_edit: bool | None = None
    """
    Flag identifying if the revision is minor.
    """

    rev_parent_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The parent revison ID of the revision that this event represents.
    """

    rev_sha1: str | None = None
    """
    The sha1 of the revision text.
    """

    rev_timestamp: Annotated[AwareDatetime, Field(max_length=128)]
    """
    The revision's creation time in ISO8601 format.  This field does not end in '_dt' to better match the field name on the Mediawiki revision table.

    """

    tags: list[str] | None = None
    """
    The list of tags after the event has happened. If the tags field is not present, the revision has no tags after the event has happened.

    """


class WikimediaEventStreamV2StreamMediawikiRevisionVisibilityChangeGetResponse(
    BaseModel
):
    """
    Represents a MW Revision Visibiilty Change event.
    """

    field_schema: Annotated[str, Field(alias="$schema")]
    """
    A URI identifying the JSONSchema for this event. This should match an schema's $id in a schema repository. E.g. /schema/title/1.0.0

    """

    chronology_id: str | None = None
    """
    Deprecated - no longer populated
    """

    comment: str | None = None
    """
    The comment left by the user that performed this change.
    """

    database: Annotated[str, Field(min_length=1)]
    """
    The name of the wiki database this event entity belongs to.
    """

    meta: WikimediaEventStreamMeta6
    page_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    """
    The page ID of the page this revision belongs to.
    """

    page_is_redirect: bool
    """
    True if this revision is a redirect.  This fact is ultimately represented by revision content containing redirect wikitext.  If this revision is the head revision of the page, then the page will also be a redirect.

    """

    page_namespace: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    """
    The namespace of the page this revision belongs to.
    """

    page_title: Annotated[str, Field(min_length=1)]
    """
    The normalized title of the page this revision belongs to.
    """

    parsedcomment: str | None = None
    """
    The comment left by the user that performed this change parsed into simple HTML. Optional

    """

    performer: WikimediaEventStreamPerformer2 | None = None
    """
    Represents the user that performed this change.
    """

    prior_state: WikimediaEventStreamPriorState10
    """
    The prior state of the entity before this event.  Revisions always have visibility settings, so this object will always contain the visibility settings for the revision before this event.

    """

    rev_content_format: str | None = None
    """
    The content format of the revision.
    """

    rev_content_model: str | None = None
    """
    The content model of the revision.
    """

    rev_id: Annotated[int, Field(ge=0, le=9007199254740991)]
    """
    The (database) revision ID.
    """

    rev_len: Annotated[int | None, Field(ge=-9007199254740991, le=9007199254740991)] = (
        None
    )
    """
    The length of the revision text in bytes.
    """

    rev_minor_edit: bool | None = None
    """
    Flag identifying if the revision is minor.
    """

    rev_parent_id: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    """
    The parent revison ID of the revision that this event represents.
    """

    rev_sha1: str | None = None
    """
    The sha1 of the revision text.
    """

    rev_timestamp: Annotated[AwareDatetime, Field(max_length=128)]
    """
    The revision's creation time in ISO8601 format.  This field does not end in '_dt' to better match the field name on the Mediawiki revision table.

    """

    visibility: WikimediaEventStreamVisibility1
    """
    The visiblity state of this revision.
    """


class WikimediaEventStreamV2StreamStreamsGetResponse(BaseModel):
    pass


class WikimediaEventStreamVisibility(BaseModel):
    """
    The prior visiblity state of this revision.
    """

    comment: bool
    text: bool
    user: bool


class WikimediaEventStreamVisibility1(BaseModel):
    """
    The visiblity state of this revision.
    """

    comment: bool
    """
    Whether the comment of the revision is visible.
    """

    text: bool
    """
    Whether the revision's text is visible.
    """

    user: bool
    """
    Whether the author of the revision's text is visible.
    """
