[project]
name = "myapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.127.1",
    "lxml>=6.0.2",
    "pygit2>=1.19.1",
    "python-multipart>=0.0.21",
    "sqlmodel>=0.0.30",
    "starlette>=0.50.0",
    "types-lxml>=2026.1.1",
    "uvicorn>=0.38.0",
]
